# Data processing for Feature Pipeline

In [154]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pprint
import pyspark
import pyspark.sql.functions as F

from pyspark.sql.functions import col
from pyspark.sql.types import StringType, IntegerType, FloatType, DateType
%load_ext autoreload
%autoreload 2
from utils.helper import generate_first_of_month_dates
import utils.data_processing_bronze_table
import utils.data_processing_silver_table

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Set up & config

In [128]:
# Initialize SparkSession
spark = pyspark.sql.SparkSession.builder \
    .appName("dev") \
    .master("local[*]") \
    .getOrCreate()

# Set log level to ERROR to hide warnings
spark.sparkContext.setLogLevel("ERROR")

In [129]:
# Setup config
start_date_str = "2023-01-01"
label_end_date_str = "2024-12-01"
snapshot_date_str = "2023-01-01"
feature_end_date_str = "2025-01-01"

In [130]:
# Generate date string list
date_str_lst = generate_first_of_month_dates(start_date_str, feature_end_date_str)

## Build bronze tables

In [73]:
# Run bronze backfill
feature_sources = {
    "attributes": "data/features_attributes.csv",
    "financials": "data/features_financials.csv",
    "clickstream": "data/feature_clickstream.csv"
}

for table_name, source_path in feature_sources.items():
    bronze_directory = f"datamart/bronze/{table_name}"
    for date in date_str_lst:
        utils.data_processing_bronze_table.process_feature_bronze_table(
            date,
            source_path,
            table_name,
            bronze_directory,
            spark
        )

2023-01-01 row count: 530
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_01_01.csv
2023-02-01 row count: 501
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_02_01.csv
2023-03-01 row count: 506
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_03_01.csv
2023-04-01 row count: 510
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_04_01.csv
2023-05-01 row count: 521
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_05_01.csv
2023-06-01 row count: 517
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_06_01.csv
2023-07-01 row count: 471
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_07_01.csv
2023-08-01 row count: 481
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_08_01.csv
2023-09-01 row count: 454
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_09_01.csv
2023-10-01 row count: 487
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_10_01.csv
2023-11-01 row count: 491
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_11_01.csv
2023-12-01 row count: 489
saved to: datamart/bronze/attributes/bronze_feature_attributes_2023_12_01.csv
2024-01-01 row count: 485
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_01_01.csv
2024-02-01 row count: 518
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_02_01.csv
2024-03-01 row count: 511
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_03_01.csv
2024-04-01 row count: 513
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_04_01.csv
2024-05-01 row count: 491
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_05_01.csv
2024-06-01 row count: 498
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_06_01.csv
2024-07-01 row count: 505
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_07_01.csv
2024-08-01 row count: 543
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_08_01.csv
2024-09-01 row count: 493
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_09_01.csv
2024-10-01 row count: 456
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_10_01.csv
2024-11-01 row count: 488
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_11_01.csv
2024-12-01 row count: 515
saved to: datamart/bronze/attributes/bronze_feature_attributes_2024_12_01.csv
2025-01-01 row count: 526
saved to: datamart/bronze/attributes/bronze_feature_attributes_2025_01_01.csv
2023-01-01 row count: 530
saved to: datamart/bronze/financials/bronze_feature_financials_2023_01_01.csv
2023-02-01 row count: 501
saved to: datamart/bronze/financials/bronze_feature_financials_2023_02_01.csv
2023-03-01 row count: 506
saved to: datamart/bronze/financials/bronze_feature_financials_2023_03_01.csv
2023-04-01 row count: 510
saved to: datamart/bronze/financials/bronze_feature_financials_2023_04_01.csv
2023-05-01 row count: 521
saved to: datamart/bronze/financials/bronze_feature_financials_2023_05_01.csv
2023-06-01 row count: 517
saved to: datamart/bronze/financials/bronze_feature_financials_2023_06_01.csv
2023-07-01 row count: 471
saved to: datamart/bronze/financials/bronze_feature_financials_2023_07_01.csv
2023-08-01 row count: 481
saved to: datamart/bronze/financials/bronze_feature_financials_2023_08_01.csv
2023-09-01 row count: 454
saved to: datamart/bronze/financials/bronze_feature_financials_2023_09_01.csv
2023-10-01 row count: 487
saved to: datamart/bronze/financials/bronze_feature_financials_2023_10_01.csv
2023-11-01 row count: 491
saved to: datamart/bronze/financials/bronze_feature_financials_2023_11_01.csv
2023-12-01 row count: 489
saved to: datamart/bronze/financials/bronze_feature_financials_2023_12_01.csv
2024-01-01 row count: 485
saved to: datamart/bronze/financials/bronze_feature_financials_2024_01_01.csv
2024-02-01 row count: 518
saved to: datamart/bronze/financials/bronze_feature_financials_2024_02_01.csv
2024-03-01 row count: 511
saved to: datamart/bronze/financials/bronze_feature_financials_2024_03_01.csv
2024-04-01 row count: 513
saved to: datamart/bronze/financials/bronze_feature_financials_2024_04_01.csv
2024-05-01 row count: 491
saved to: datamart/bronze/financials/bronze_feature_financials_2024_05_01.csv
2024-06-01 row count: 498
saved to: datamart/bronze/financials/bronze_feature_financials_2024_06_01.csv
2024-07-01 row count: 505
saved to: datamart/bronze/financials/bronze_feature_financials_2024_07_01.csv
2024-08-01 row count: 543
saved to: datamart/bronze/financials/bronze_feature_financials_2024_08_01.csv
2024-09-01 row count: 493
saved to: datamart/bronze/financials/bronze_feature_financials_2024_09_01.csv
2024-10-01 row count: 456
saved to: datamart/bronze/financials/bronze_feature_financials_2024_10_01.csv
2024-11-01 row count: 488
saved to: datamart/bronze/financials/bronze_feature_financials_2024_11_01.csv
2024-12-01 row count: 515
saved to: datamart/bronze/financials/bronze_feature_financials_2024_12_01.csv
2025-01-01 row count: 526
saved to: datamart/bronze/financials/bronze_feature_financials_2025_01_01.csv
2023-01-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_01_01.csv
2023-02-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_02_01.csv
2023-03-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_03_01.csv
2023-04-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_04_01.csv
2023-05-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_05_01.csv
2023-06-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_06_01.csv
2023-07-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_07_01.csv
2023-08-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_08_01.csv
2023-09-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_09_01.csv
2023-10-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_10_01.csv
2023-11-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_11_01.csv
2023-12-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_12_01.csv
2024-01-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_01_01.csv
2024-02-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_02_01.csv
2024-03-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_03_01.csv
2024-04-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_04_01.csv
2024-05-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_05_01.csv
2024-06-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_06_01.csv
2024-07-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_07_01.csv
2024-08-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_08_01.csv
2024-09-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_09_01.csv
2024-10-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_10_01.csv
2024-11-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_11_01.csv
2024-12-01 row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_12_01.csv
2025-01-01 row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_01_01.csv

## EDA & Silver preparation for `features_attributes` data

**Goal**: Use EDA to justify the cleaning rules, then build a clean Silver dataframe.

- Keep `customer_id` as the entity/join key;
- Clean `age`;
- Clean `occupation`;
- Keep and validate `snapshot_date` for temporal alignment;
- Exclude `Name` and `SSN` from Silver because they are PII and are not required for downstream feature generation. The raw values remain available in Bronze.

### 1. Exploration at file-level

Confirm that the Bronze partitions have the expected structure and that `Customer_ID` is unique within each snapshot.

In [74]:
# Explore data at file-level
attributes_dir = "datamart/bronze/attributes"
attribute_files = sorted(glob.glob(os.path.join(attributes_dir, "*.csv")))

results = []

for file_path in attribute_files:
    file_name = os.path.basename(file_path)

    # Expected Bronze naming: bronze_attributes_YYYY_MM_DD.csv
    snapshot_date = file_name.replace("bronze_feature_attributes_", "").replace(".csv", "")

    # Read Bronze consistently as strings; type casting will be enforced in Silver
    df = spark.read.csv(file_path, header=True, inferSchema=False)

    row_count = df.count()
    column_count = len(df.columns)
    distinct_customer_count = df.select("customer_id").distinct().count()

    results.append({
        "snapshot_date": snapshot_date,
        "row_number": row_count,
        "column_number": column_count,
        "distinct_customer_id": distinct_customer_count,
        "customer_id_unique_within_snapshot": (
            row_count == distinct_customer_count
        )
    })

attributes_summary = pd.DataFrame(results).sort_values("snapshot_date")
attributes_summary

,snapshot_date,row_number,column_number,distinct_customer_id,customer_id_unique_within_snapshot
0,2023_01_01,530,6,530,True
1,2023_02_01,501,6,501,True
2,2023_03_01,506,6,506,True
3,2023_04_01,510,6,510,True
4,2023_05_01,521,6,521,True
5,2023_06_01,517,6,517,True
6,2023_07_01,471,6,471,True
7,2023_08_01,481,6,481,True
8,2023_09_01,454,6,454,True
9,2023_10_01,487,6,487,True
10,2023_11_01,491,6,491,True
11,2023_12_01,489,6,489,True
12,2024_01_01,485,6,485,True
13,2024_02_01,518,6,518,True
14,2024_03_01,511,6,511,True
15,2024_04_01,513,6,513,True
16,2024_05_01,491,6,491,True
17,2024_06_01,498,6,498,True
18,2024_07_01,505,6,505,True
19,2024_08_01,543,6,543,True
20,2024_09_01,493,6,493,True
21,2024_10_01,456,6,456,True
22,2024_11_01,488,6,488,True
23,2024_12_01,515,6,515,True
24,2025_01_01,526,6,526,True

**Observations**: 6 source columns in every Bronze partition, `Customer_id` is unique in each partition. From here on, all 25 partitions are loaded as one table so each column can be profiled across the full dataset

### 2. Exploration  at union-level

In [75]:
# Union all partitions into one dataframe
attribute_dfs = [
    spark.read.csv(file_path, header=True, inferSchema=False)
    for file_path in attribute_files
]

attributes_df = attribute_dfs[0]
for partition_df in attribute_dfs[1:]:
    attributes_df = attributes_df.unionByName(partition_df)

print(f"Total rows: {attributes_df.count()}")
attributes_df.printSchema()
attributes_df.show(5, truncate=False)

Total rows: 12500
root
 |-- Customer_ID: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: string (nullable = true)
 |-- SSN: string (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- snapshot_date: string (nullable = true)

+-----------+---------------+---+-----------+----------+-------------+
|Customer_ID|Name           |Age|SSN        |Occupation|snapshot_date|
+-----------+---------------+---+-----------+----------+-------------+
|CUS_0x1037 |Matthewm       |45 |230-22-9583|Accountant|2023-01-01   |
|CUS_0x1069 |Andreas Cremero|32 |761-27-5143|Accountant|2023-01-01   |
|CUS_0x114a |Valetkevitchu  |43 |133-89-5234|Developer |2023-01-01   |
|CUS_0x1184 |Cohenq         |49 |963-76-2464|Lawyer    |2023-01-01   |
|CUS_0x1297 |Edwardsz       |46 |#F%$D@*&8  |Manager   |2023-01-01   |
+-----------+---------------+---+-----------+----------+-------------+
only showing top 5 rows

#### 2.1. Check duplicates

In [76]:
# Number of rows
total_rows = attributes_df.count()

# Number of exact duplicate rows (excluding the first occurrence)
exact_duplicate_rows = (
    attributes_df.groupBy(attributes_df.columns)
    .count()
    .filter(F.col("count") > 1)
    .select(F.sum(F.col("count") - 1).alias("duplicate_rows"))
    .first()["duplicate_rows"] or 0
)

# Number of duplicated (snapshot_date, customer_id) pairs
duplicated_pairs = (
    attributes_df.groupBy("snapshot_date", "Customer_ID")
    .count()
    .filter(F.col("count") > 1)
    .count()
)

null_customer_id = attributes_df.filter(F.col("Customer_ID").isNull()).count()
null_snapshot_date = attributes_df.filter(F.col("snapshot_date").isNull()).count()

print(f"Number of rows: {total_rows}")
print(f"Number of exact duplicated rows: {exact_duplicate_rows}")
print(f"Number of duplicated (snapshot_date, customer_id) pairs: {duplicated_pairs}")
print(f"Null Customer_ID: {null_customer_id}")
print(f"Null snapshot_date: {null_snapshot_date}")

Number of rows: 12500
Number of exact duplicated rows: 0
Number of duplicated (snapshot_date, customer_id) pairs: 0
Null Customer_ID: 0
Null snapshot_date: 0

#### 2.2. Scan generic missing values (null-like strings)

In [77]:
# Values treated as missing, regardless of letter case
missing_values = ("", "unknown", "n/a", "na", "nan", "null", "none")

missing_count_expressions = []

for column_name in attributes_df.columns:
    column_text = F.lower(
        F.trim(F.col(column_name).cast("string"))
    )
    is_missing = (
        F.col(column_name).isNull()
        | column_text.isin(*missing_values)
    )

    missing_count_expressions.append(
        F.sum(F.when(is_missing, 1).otherwise(0)).alias(column_name)
    )

attributes_df.select(*missing_count_expressions).show(truncate=False)

+-----------+----+---+---+----------+-------------+
|Customer_ID|Name|Age|SSN|Occupation|snapshot_date|
+-----------+----+---+---+----------+-------------+
|0          |0   |0  |0  |0         |0            |
+-----------+----+---+---+----------+-------------+

### 3. Clean `Age` column

#### 3.1. Inspect raw data

In [78]:
print("Age source datatype:")
print(attributes_df.schema["Age"])

Age source datatype:
StructField('Age', StringType(), True)

In [57]:
# Check rows that are not numeric
age_invalid = attributes_df.filter(
    ~F.col("Age").rlike(r"^\d+$")
)

age_invalid.select("Age").show(50, truncate=False)
print(f"Invalid Age rows: {age_invalid.count()}")

+-----+
|Age  |
+-----+
|41_  |
|-500 |
|2329_|
|38_  |
|39_  |
|18_  |
|28_  |
|15_  |
|45_  |
|26_  |
|31_  |
|-500 |
|42_  |
|23_  |
|48_  |
|45_  |
|-500 |
|29_  |
|-500 |
|-500 |
|-500 |
|43_  |
|32_  |
|34_  |
|21_  |
|35_  |
|-500 |
|31_  |
|37_  |
|43_  |
|43_  |
|-500 |
|21_  |
|43_  |
|27_  |
|25_  |
|45_  |
|7723_|
|41_  |
|-500 |
|-500 |
|14_  |
|38_  |
|51_  |
|43_  |
|44_  |
|35_  |
|-500 |
|55_  |
|35_  |
+-----+
only showing top 50 rows

Invalid Age rows: 741

**Observations:** `age` contains anomalies:
- Trailing underscores, e.g. `41_`, `2329_`  ==> Formatting issues
- Negative values, e.g: -500  ==> Invalid value

In [81]:
# Values containing an underscore
age_with_underscore = attributes_df.filter(
    F.col("Age").contains("_")
)

# Confirm the underscore pattern is only trailing underscores.
unexpected_underscore_pattern = attributes_df.filter(
    F.col("Age").contains("_")
    & ~F.col("Age").rlike(r"^-?\d+_+$")
)

print(f"Rows containing underscore: {age_with_underscore.count()}")
print(
    "Rows where underscore is NOT a simple trailing-suffix pattern: "
    f"{unexpected_underscore_pattern.count()}"
)

age_with_underscore.select("Age").distinct().orderBy("Age").show(10, truncate=False)

Rows containing underscore: 637
Rows where underscore is NOT a simple trailing-suffix pattern: 0
+-----+
|Age  |
+-----+
|1070_|
|1248_|
|14_  |
|15_  |
|16_  |
|17_  |
|18_  |
|19_  |
|20_  |
|21_  |
+-----+
only showing top 10 rows

#### 3.2. Handle formatting issue & cast to integer

In [85]:
age_profile_df = (
    attributes_df
    # Remove trailing underscore
    .withColumn(
        "age_normalized",
        F.regexp_replace(F.trim(F.col("Age")), r"_+$", "")
    )
    # Cast to integer
    .withColumn(
        "age_parsed",
        F.col("age_normalized").cast(IntegerType())
    )
)

# Verify that the formatting normalisation did not create unparseable ages.
age_profile_df.filter(
    F.col("Age").isNotNull() & F.col("age_parsed").isNull()
).select("Age", "age_normalized").show(50, truncate=False)

print(
    "Rows that could not be parsed after normalisation: "
    f"{age_profile_df.filter(F.col('Age').isNotNull() & F.col('age_parsed').isNull()).count()}"
)


print("Rows after normalisation and parsing:")
age_profile_df.select('Age', 'age_normalized', 'age_parsed').show()

+---+--------------+
|Age|age_normalized|
+---+--------------+
+---+--------------+

Rows that could not be parsed after normalisation: 0
Rows after normalisation and parsing:
+---+--------------+----------+
|Age|age_normalized|age_parsed|
+---+--------------+----------+
| 45|            45|        45|
| 32|            32|        32|
| 43|            43|        43|
| 49|            49|        49|
| 46|            46|        46|
| 35|            35|        35|
| 27|            27|        27|
| 47|            47|        47|
| 15|            15|        15|
|41_|            41|        41|
| 52|            52|        52|
| 19|            19|        19|
| 31|            31|        31|
| 29|            29|        29|
| 36|            36|        36|
| 20|            20|        20|
| 31|            31|        31|
| 27|            27|        27|
| 35|            35|        35|
| 46|            46|        46|
+---+--------------+----------+
only showing top 20 rows

#### 3.3. Inspect range of `Age`

**Business sense:**
- Negative values (e.g: -500) and ages above 100 are implausible ==> Convert to Null
- Values < 18 does not make sense in business & legal context ==> Retain as observed in Silver and flag for Gold

In [88]:
# Overall range checks
age_counts = age_profile_df.select(
    F.sum(F.when(F.col("age_parsed") < 0, 1).otherwise(0))
        .alias("count_age_below_0"),
    F.sum(F.when(F.col("age_parsed") < 18, 1).otherwise(0))
        .alias("count_age_below_18"),
    F.sum(F.when(F.col("age_parsed") > 100, 1).otherwise(0))
        .alias("count_age_above_100")
)

age_counts.show()


# Inspect frequencies outside the expected 0-100 quality range
(
    age_profile_df
    .filter(
        (F.col("age_parsed") < 0)
        | (F.col("age_parsed") > 100)
        | (F.col("age_parsed") < 18)
    )
    .groupBy("age_parsed")
    .count()
    .orderBy("age_parsed")
    .show(150, truncate=False)
)

+-----------------+------------------+-------------------+
|count_age_below_0|count_age_below_18|count_age_above_100|
+-----------------+------------------+-------------------+
|              104|               773|                215|
+-----------------+------------------+-------------------+

+----------+-----+
|age_parsed|count|
+----------+-----+
|-500      |104  |
|14        |87   |
|15        |195  |
|16        |189  |
|17        |198  |
|169       |1    |
|203       |1    |
|210       |1    |
|236       |1    |
|305       |1    |
|306       |1    |
|325       |1    |
|335       |1    |
|344       |1    |
|395       |1    |
|448       |1    |
|506       |1    |
|509       |1    |
|581       |1    |
|598       |1    |
|655       |2    |
|813       |1    |
|831       |1    |
|886       |1    |
|925       |1    |
|1004      |1    |
|1022      |1    |
|1066      |1    |
|1070      |1    |
|1087      |1    |
|1094      |1    |
|1149      |1    |
|1203      |1    |
|1220      |1    |
|1248      |1    |
|1265      |1    |
|1388      |1    |
|1418      |1    |
|1520      |1    |
|1683      |1    |
|1733      |1    |
|1792      |1    |
|1810      |1    |
|1814      |1    |
|1990      |1    |
|2038      |1    |
|2048      |1    |
|2090      |1    |
|2109      |1    |
|2160      |1    |
|2170      |1    |
|2178      |1    |
|2318      |1    |
|2329      |1    |
|2347      |1    |
|2405      |1    |
|2513      |1    |
|2534      |1    |
|2543      |1    |
|2546      |1    |
|2580      |1    |
|2593      |1    |
|2598      |1    |
|2604      |1    |
|2672      |1    |
|2749      |1    |
|2778      |1    |
|2823      |1    |
|2932      |1    |
|2952      |1    |
|2997      |1    |
|3038      |1    |
|3052      |1    |
|3115      |1    |
|3125      |1    |
|3264      |1    |
|3274      |1    |
|3367      |1    |
|3441      |1    |
|3493      |1    |
|3502      |1    |
|3513      |1    |
|3537      |1    |
|3553      |1    |
|3610      |1    |
|3638      |1    |
|3640      |1    |
|3764      |1    |
|3791      |1    |
|3834      |1    |
|3843      |1    |
|3856      |1    |
|3899      |1    |
|3920      |1    |
|3984      |1    |
|3986      |1    |
|4021      |1    |
|4049      |1    |
|4050      |1    |
|4056      |1    |
|4120      |1    |
|4133      |1    |
|4177      |1    |
|4188      |1    |
|4212      |1    |
|4301      |1    |
|4351      |1    |
|4391      |1    |
|4431      |1    |
|4458      |1    |
|4536      |1    |
|4566      |1    |
|4592      |1    |
|4630      |1    |
|4670      |1    |
|4679      |1    |
|4710      |1    |
|4746      |1    |
|4820      |1    |
|4862      |1    |
|4881      |1    |
|4897      |1    |
|4909      |1    |
|4929      |1    |
|5018      |1    |
|5027      |1    |
|5177      |1    |
|5194      |1    |
|5195      |1    |
|5261      |1    |
|5301      |1    |
|5316      |1    |
|5340      |1    |
|5376      |1    |
|5422      |1    |
|5471      |1    |
|5498      |1    |
|5504      |1    |
|5509      |1    |
|5568      |1    |
|5629      |1    |
|5643      |1    |
|5645      |1    |
|5656      |1    |
|5714      |1    |
|5751      |1    |
|5784      |1    |
|5798      |1    |
|5959      |1    |
|5981      |1    |
+----------+-----+
only showing top 150 rows

In [89]:
# Apply the Silver cleaning rule for Age (replace value <0 and >100 with null)
age_clean_df = (
    age_profile_df
    .withColumn(
        "age_clean",
        F.when(
            (F.col("age_parsed") < 0)
            | (F.col("age_parsed") > 100),
            F.lit(None).cast(IntegerType())
        ).otherwise(F.col("age_parsed"))
    )
)

# Validate the rule
remaining_invalid_age = age_clean_df.filter(
    (F.col("age_clean") < 0) | (F.col("age_clean") > 100)
).count()

print(f"Remaining impossible age values: {remaining_invalid_age}")
print(
    "Age values converted to NULL: "
    f"{age_clean_df.filter(F.col('age_clean').isNull()).count()}"
)

Remaining impossible age values: 0
Age values converted to NULL: 319

### 4. Clean `Occupation` column

#### 4.1. Inspect raw data & profile categories

In [63]:
attributes_df.groupBy("Occupation").count().orderBy(F.desc("count")).show()

+-------------+-----+
|   Occupation|count|
+-------------+-----+
|      _______|  880|
|       Lawyer|  828|
|    Architect|  795|
|     Engineer|  793|
|   Accountant|  791|
|    Scientist|  789|
|      Teacher|  782|
|Media_Manager|  780|
|    Developer|  780|
|     Mechanic|  780|
| Entrepreneur|  776|
|   Journalist|  761|
|       Doctor|  760|
|     Musician|  741|
|      Manager|  736|
|       Writer|  728|
+-------------+-----+

#### 4.2. Handle placeholder

Convert placeholder `_______` to Null, retain valid category names as they are

In [93]:
occupation_clean_df = (
    age_clean_df
    .withColumn(
        "occupation_clean",
        F.when(
            F.trim(F.col("Occupation")) == "_______",
            F.lit(None).cast(StringType())
        ).otherwise(F.trim(F.col("Occupation")))
    )
)

print(
    "Occupation NULL count after cleaning: "
    f"{occupation_clean_df.filter(F.col('occupation_clean').isNull()).count()}"
)

(
    occupation_clean_df
    .groupBy("occupation_clean")
    .count()
    .orderBy(F.desc("count"))
    .show(100, truncate=False)
)

Occupation NULL count after cleaning: 880
+----------------+-----+
|occupation_clean|count|
+----------------+-----+
|NULL            |880  |
|Lawyer          |828  |
|Architect       |795  |
|Engineer        |793  |
|Accountant      |791  |
|Scientist       |789  |
|Teacher         |782  |
|Media_Manager   |780  |
|Developer       |780  |
|Mechanic        |780  |
|Entrepreneur    |776  |
|Journalist      |761  |
|Doctor          |760  |
|Musician        |741  |
|Manager         |736  |
|Writer          |728  |
+----------------+-----+

### Build Silver `features_attributes` table

| Source column | Silver decision | Reason |
|---|---|---|
| `Customer_ID` | Keep → `customer_id` | Entity key for joins |
| `Name` | Drop | PII; not required for ML features |
| `Age` | Keep cleaned → `age` | Candidate model feature |
| `SSN` | Drop | Sensitive PII; not required for ML features |
| `Occupation` | Keep cleaned → `occupation` | Candidate model feature |
| `snapshot_date` | Keep as `DateType` | Temporal alignment / leakage control |

In [97]:
silver_attributes_df = (
    occupation_clean_df
    .withColumn(
        "customer_id",
        F.trim(F.col("Customer_ID")).cast(StringType())
    )
    .withColumn(
        "snapshot_date_clean",
        F.to_date(F.col("snapshot_date"), "yyyy-MM-dd")
    )
    .select(
        "customer_id",
        F.col("age_clean").alias("age"),
        F.col("occupation_clean").alias("occupation"),
        F.col("snapshot_date_clean").alias("snapshot_date")
    )
)

silver_attributes_df.printSchema()
silver_attributes_df.show(20, truncate=False)

root
 |-- customer_id: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- occupation: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+-----------+---+-------------+-------------+
|customer_id|age|occupation   |snapshot_date|
+-----------+---+-------------+-------------+
|CUS_0x1037 |45 |Accountant   |2023-01-01   |
|CUS_0x1069 |32 |Accountant   |2023-01-01   |
|CUS_0x114a |43 |Developer    |2023-01-01   |
|CUS_0x1184 |49 |Lawyer       |2023-01-01   |
|CUS_0x1297 |46 |Manager      |2023-01-01   |
|CUS_0x12fb |35 |Doctor       |2023-01-01   |
|CUS_0x1325 |27 |Accountant   |2023-01-01   |
|CUS_0x1341 |47 |Mechanic     |2023-01-01   |
|CUS_0x1375 |15 |Lawyer       |2023-01-01   |
|CUS_0x13a8 |41 |Journalist   |2023-01-01   |
|CUS_0x13ef |52 |Media_Manager|2023-01-01   |
|CUS_0x1440 |19 |Teacher      |2023-01-01   |
|CUS_0x1443 |31 |Lawyer       |2023-01-01   |
|CUS_0x145a |29 |Lawyer       |2023-01-01   |
|CUS_0x1492 |36 |Teacher      |2023-01-01   |
|CUS_0x153d |20 |Accountant   |2023-01-01   |
|CUS_0x1567 |31 |Entrepreneur |2023-01-01   |
|CUS_0x15ad |27 |Mechanic     |2023-01-01   |
|CUS_0x1630 |35 |Writer       |2023-01-01   |
|CUS_0x169c |46 |Developer    |2023-01-01   |
+-----------+---+-------------+-------------+
only showing top 20 rows

In [100]:
# Validation against Bronze to ensure no rows are accidentally removed

bronze_row_count = attributes_df.count()
silver_row_count = silver_attributes_df.count()

silver_null_summary = silver_attributes_df.select(
    *[
        F.sum(F.when(F.col(c).isNull(), 1).otherwise(0)).alias(c)
        for c in silver_attributes_df.columns
    ]
)

print(f"Bronze rows: {bronze_row_count}")
print(f"Silver rows: {silver_row_count}")
print(f"Row count preserved: {bronze_row_count == silver_row_count}")
print("Null counts after Silver cleaning:")
silver_null_summary.show(truncate=False)

Bronze rows: 12500
Silver rows: 12500
Row count preserved: True
Null counts after Silver cleaning:
+-----------+---+----------+-------------+
|customer_id|age|occupation|snapshot_date|
+-----------+---+----------+-------------+
|0          |319|880       |0            |
+-----------+---+----------+-------------+

## Build Silver tables for `feature_attributes`

In [7]:
bronze_directory = "datamart/bronze/attributes"
silver_directory = "datamart/silver/attributes"

for snapshot_date in date_str_lst:
    utils.data_processing_silver_table.process_feature_attributes_silver_table(
        snapshot_date,
        bronze_directory,
        silver_directory,
        spark
    )

loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_01_01.csv row count: 530

saved to: datamart/silver/attributes/silver_feature_attributes_2023_01_01.parquet row count: 530
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_02_01.csv row count: 501
saved to: datamart/silver/attributes/silver_feature_attributes_2023_02_01.parquet row count: 501
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_03_01.csv row count: 506
saved to: datamart/silver/attributes/silver_feature_attributes_2023_03_01.parquet row count: 506
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_04_01.csv row count: 510
saved to: datamart/silver/attributes/silver_feature_attributes_2023_04_01.parquet row count: 510
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_05_01.csv row count: 521
saved to: datamart/silver/attributes/silver_feature_attributes_2023_05_01.parquet row count: 521
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_06_01.csv row count: 517
saved to: datamart/silver/attributes/silver_feature_attributes_2023_06_01.parquet row count: 517
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_07_01.csv row count: 471
saved to: datamart/silver/attributes/silver_feature_attributes_2023_07_01.parquet row count: 471
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_08_01.csv row count: 481
saved to: datamart/silver/attributes/silver_feature_attributes_2023_08_01.parquet row count: 481
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_09_01.csv row count: 454
saved to: datamart/silver/attributes/silver_feature_attributes_2023_09_01.parquet row count: 454
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_10_01.csv row count: 487
saved to: datamart/silver/attributes/silver_feature_attributes_2023_10_01.parquet row count: 487
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_11_01.csv row count: 491
saved to: datamart/silver/attributes/silver_feature_attributes_2023_11_01.parquet row count: 491
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2023_12_01.csv row count: 489
saved to: datamart/silver/attributes/silver_feature_attributes_2023_12_01.parquet row count: 489
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_01_01.csv row count: 485
saved to: datamart/silver/attributes/silver_feature_attributes_2024_01_01.parquet row count: 485
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_02_01.csv row count: 518
saved to: datamart/silver/attributes/silver_feature_attributes_2024_02_01.parquet row count: 518
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_03_01.csv row count: 511
saved to: datamart/silver/attributes/silver_feature_attributes_2024_03_01.parquet row count: 511
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_04_01.csv row count: 513
saved to: datamart/silver/attributes/silver_feature_attributes_2024_04_01.parquet row count: 513
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_05_01.csv row count: 491
saved to: datamart/silver/attributes/silver_feature_attributes_2024_05_01.parquet row count: 491
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_06_01.csv row count: 498
saved to: datamart/silver/attributes/silver_feature_attributes_2024_06_01.parquet row count: 498
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_07_01.csv row count: 505
saved to: datamart/silver/attributes/silver_feature_attributes_2024_07_01.parquet row count: 505
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_08_01.csv row count: 543
saved to: datamart/silver/attributes/silver_feature_attributes_2024_08_01.parquet row count: 543
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_09_01.csv row count: 493
saved to: datamart/silver/attributes/silver_feature_attributes_2024_09_01.parquet row count: 493
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_10_01.csv row count: 456
saved to: datamart/silver/attributes/silver_feature_attributes_2024_10_01.parquet row count: 456
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_11_01.csv row count: 488
saved to: datamart/silver/attributes/silver_feature_attributes_2024_11_01.parquet row count: 488
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2024_12_01.csv row count: 515
saved to: datamart/silver/attributes/silver_feature_attributes_2024_12_01.parquet row count: 515
loaded from: datamart/bronze/attributes/bronze_feature_attributes_2025_01_01.csv row count: 526
saved to: datamart/silver/attributes/silver_feature_attributes_2025_01_01.parquet row count: 526

## EDA & Silver Preparation for `feature_financials`

### 1. Exploration at file-leve

In [94]:
# Explore data at file-level
financials_dir = "datamart/bronze/financials"
financials_files = sorted(glob.glob(os.path.join(financials_dir, "*.csv")))

results = []

for file_path in financials_files:
    file_name = os.path.basename(file_path)

    # Expected Bronze naming: bronze_attributes_YYYY_MM_DD.csv
    snapshot_date = file_name.replace("bronze_feature_financials_", "").replace(".csv", "")

    # Read Bronze consistently as strings; type casting will be enforced in Silver
    df = spark.read.csv(file_path, header=True, inferSchema=False)

    row_count = df.count()
    column_count = len(df.columns)
    distinct_customer_count = df.select("customer_id").distinct().count()

    results.append({
        "snapshot_date": snapshot_date,
        "row_number": row_count,
        "column_number": column_count,
        "distinct_customer_id": distinct_customer_count,
        "customer_id_unique_within_snapshot": (
            row_count == distinct_customer_count
        )
    })

financials_summary = pd.DataFrame(results).sort_values("snapshot_date")
financials_summary

,snapshot_date,row_number,column_number,distinct_customer_id,customer_id_unique_within_snapshot
0,2023_01_01,530,22,530,True
1,2023_02_01,501,22,501,True
2,2023_03_01,506,22,506,True
3,2023_04_01,510,22,510,True
4,2023_05_01,521,22,521,True
5,2023_06_01,517,22,517,True
6,2023_07_01,471,22,471,True
7,2023_08_01,481,22,481,True
8,2023_09_01,454,22,454,True
9,2023_10_01,487,22,487,True
10,2023_11_01,491,22,491,True
11,2023_12_01,489,22,489,True
12,2024_01_01,485,22,485,True
13,2024_02_01,518,22,518,True
14,2024_03_01,511,22,511,True
15,2024_04_01,513,22,513,True
16,2024_05_01,491,22,491,True
17,2024_06_01,498,22,498,True
18,2024_07_01,505,22,505,True
19,2024_08_01,543,22,543,True
20,2024_09_01,493,22,493,True
21,2024_10_01,456,22,456,True
22,2024_11_01,488,22,488,True
23,2024_12_01,515,22,515,True
24,2025_01_01,526,22,526,True

### 2. Exploration at union-level

In [ ]:
# Union all partitions into one dataframe
financials_dfs = [
    spark.read.csv(file_path, header=True, inferSchema=False)
    for file_path in financials_files
]

financials_df = financials_dfs[0]
for partition_df in financials_dfs[1:]:
    financials_df = financials_df.unionByName(partition_df)

print(f"Total rows: {financials_df.count()}")
financials_df.printSchema()
financials_df.show(5, truncate=False)

Total rows: 12500
root
 |-- Customer_ID: string (nullable = true)
 |-- Annual_Income: string (nullable = true)
 |-- Monthly_Inhand_Salary: string (nullable = true)
 |-- Num_Bank_Accounts: string (nullable = true)
 |-- Num_Credit_Card: string (nullable = true)
 |-- Interest_Rate: string (nullable = true)
 |-- Num_of_Loan: string (nullable = true)
 |-- Type_of_Loan: string (nullable = true)
 |-- Delay_from_due_date: string (nullable = true)
 |-- Num_of_Delayed_Payment: string (nullable = true)
 |-- Changed_Credit_Limit: string (nullable = true)
 |-- Num_Credit_Inquiries: string (nullable = true)
 |-- Credit_Mix: string (nullable = true)
 |-- Outstanding_Debt: string (nullable = true)
 |-- Credit_Utilization_Ratio: string (nullable = true)
 |-- Credit_History_Age: string (nullable = true)
 |-- Payment_of_Min_Amount: string (nullable = true)
 |-- Total_EMI_per_month: string (nullable = true)
 |-- Amount_invested_monthly: string (nullable = true)
 |-- Payment_Behaviour: string (nullable = true)
 |-- Monthly_Balance: string (nullable = true)
 |-- snapshot_date: string (nullable = true)

+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+--------------------------------+------------------+-------------+
|Customer_ID|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|Type_of_Loan                                                                                                                               |Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Credit_History_Age   |Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|Payment_Behaviour               |Monthly_Balance   |snapshot_date|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+--------------------------------+------------------+-------------+
|CUS_0x1037 |15989.085    |1086.42375           |5                |4              |2            |4          |Credit-Builder Loan, Auto Loan, Auto Loan, and Mortgage Loan                                                                               |13                 |15                    |0.5                 |3.0                 |Good      |665.82          |40.69769934536393       |19 Years and 9 Months|No                   |33.797020629881075 |80.46523951443457      |Low_spent_Small_value_payments  |284.3801148556844 |2023-01-01   |
|CUS_0x1069 |58637.34     |4799.445             |4                |6              |10           |119        |Personal Loan, Auto Loan, and Not Specified                                                                                                |9                  |17                    |12.56               |5.0                 |Standard  |208.8           |25.23314363376225       |30 Years and 8 Months|Yes                  |139.8850133927109  |165.21061289035896     |High_spent_Small_value_payments |434.8488737169301 |2023-01-01   |
|CUS_0x114a |15305.46     |1230.455             |0                |7              |2            |2          |Student Loan, and Home Equity Loan                                                                                                         |14                 |2                     |15.95               |0.0                 |Good      |642.42_         |27.52511297681479       |15 Years and 9 Months|No                   |20.301653868439384 |64.77848007633177      |Low_spent_Small_value_payments  |327.96536605522886|2023-01-01   |
|CUS_0x1184 |19867.475    |1396.6229166666665   |3                |5              |11           |3          |Student Loan, Mortgage Loan, and Payday Loan                                                                                               |10                 |9                     |6.74                |4.0                 |Good      |707.29          |26.68978981173729       |32 Years and 8 Months|No                   |42.60688196261637  |23.460944042729498     |!@9#%8                          |313.5944656613208 |2023-01-01   |
|CUS_0x1297 |57738.06_    |4881.505             |9                |8              |30           |9          |Payday Loan, Personal Loan, Payday Loan, Personal Loan, Mortgage Loan, Home Equity Loan, Student Loan, Credit-Builder Loan, and Payday Loan|61                 |24                    |14.27               |11.0                |Bad       |3916.47         |25.74214265617326       |13 Years and 8 Months|Yes                  |296.2841357039575  |53.82117764831425      |High_spent_Medium_value_payments|388.04518664772837|2023-01-01   |
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+---------------------+-------------------+-----------------------+--------------------------------+------------------+-------------+
only showing top 5 rows

#### 2.1. Check duplicates

In [96]:
# Number of exact duplicate rows (excluding the first occurrence)
exact_duplicate_rows = (
    financials_df.groupBy(financials_df.columns)
    .count()
    .filter(F.col("count") > 1)
    .select(F.sum(F.col("count") - 1).alias("duplicate_rows"))
    .first()["duplicate_rows"] or 0
)

# Number of duplicated (snapshot_date, customer_id) pairs
duplicated_pairs = (
    financials_df.groupBy("snapshot_date", "Customer_ID")
    .count()
    .filter(F.col("count") > 1)
    .count()
)

null_customer_id = financials_df.filter(F.col("Customer_ID").isNull()).count()
null_snapshot_date = financials_df.filter(F.col("snapshot_date").isNull()).count()

print(f"Number of exact duplicated rows: {exact_duplicate_rows}")
print(f"Number of duplicated (snapshot_date, customer_id) pairs: {duplicated_pairs}")
print(f"Null Customer_ID: {null_customer_id}")
print(f"Null snapshot_date: {null_snapshot_date}")

Number of exact duplicated rows: 0
Number of duplicated (snapshot_date, customer_id) pairs: 0
Null Customer_ID: 0
Null snapshot_date: 0

#### 2.2. Scan generic missing values

In [97]:
# Values treated as missing, regardless of letter case
missing_values = ("", "unknown", "n/a", "na", "nan", "null", "none")

missing_count_expressions = []

for column_name in financials_df.columns:
    column_text = F.lower(
        F.trim(F.col(column_name).cast("string"))
    )
    is_missing = (
        F.col(column_name).isNull()
        | column_text.isin(*missing_values)
    )

    missing_count_expressions.append(
        F.sum(F.when(is_missing, 1).otherwise(0)).alias(column_name)
    )

financials_df.select(*missing_count_expressions).show(truncate=False)

+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+------------------+---------------------+-------------------+-----------------------+-----------------+---------------+-------------+
|Customer_ID|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|Type_of_Loan|Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Credit_History_Age|Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|Payment_Behaviour|Monthly_Balance|snapshot_date|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+------------------+---------------------+-------------------+-----------------------+-----------------+---------------+-------------+
|0          |0            |0                    |0                |0              |0            |0          |1426        |0                  |0                     |0                   |0                   |0         |0               |0                       |0                 |0                    |0                  |0                      |0                |0              |0            |
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+------------------+---------------------+-------------------+-----------------------+-----------------+---------------+-------------+

#### 2.3. Inspect numeric columns

In [98]:
# Numeric columns stored as text in Bronze, with their target Silver type
numeric_columns = {
    "Annual_Income": FloatType(),
    "Monthly_Inhand_Salary": FloatType(),
    "Num_Bank_Accounts": IntegerType(),
    "Num_Credit_Card": IntegerType(),
    "Interest_Rate": IntegerType(),
    "Num_of_Loan": IntegerType(),
    "Delay_from_due_date": IntegerType(),
    "Num_of_Delayed_Payment": IntegerType(),
    "Changed_Credit_Limit": FloatType(),
    "Num_Credit_Inquiries": IntegerType(),
    "Outstanding_Debt": FloatType(),
    "Credit_Utilization_Ratio": FloatType(),
    "Total_EMI_per_month": FloatType(),
    "Amount_invested_monthly": FloatType(),
    "Monthly_Balance": FloatType(),
}

numeric_pattern = r"^-?\d+(\.\d+)?$"

invalid_numeric_results = []

for column_name in numeric_columns:
    invalid_df = financials_df.filter(~F.trim(F.col(column_name)).rlike(numeric_pattern))
    examples = [
        row[column_name]
        for row in invalid_df.groupBy(column_name).count()
                             .orderBy(F.desc("count")).limit(5).collect()
    ]
    invalid_numeric_results.append({
        "column": column_name,
        "non_numeric_rows": invalid_df.count(),
        "top_examples": examples
    })

pd.set_option("display.max_colwidth", 80)
pd.DataFrame(invalid_numeric_results)

,column,non_numeric_rows,top_examples
0,Annual_Income,859,"[58511.78_, 88120.12_, 57738.06_, 17290.42_, 63847.8_]"
1,Monthly_Inhand_Salary,0,[]
2,Num_Bank_Accounts,0,[]
3,Num_Credit_Card,0,[]
4,Interest_Rate,0,[]
5,Num_of_Loan,623,"[2_, 4_, 3_, 0_, 1_]"
6,Delay_from_due_date,0,[]
7,Num_of_Delayed_Payment,374,"[18_, 19_, 20_, 15_, 12_]"
8,Changed_Credit_Limit,254,[_]
9,Num_Credit_Inquiries,0,[]
10,Outstanding_Debt,139,"[1268.49_, 149.92_, 642.42_, 2483.98_, 1333.49_]"
11,Credit_Utilization_Ratio,0,[]
12,Total_EMI_per_month,0,[]
13,Amount_invested_monthly,558,[__10000__]
14,Monthly_Balance,1,[__-333333333333333333333333333__]

**Observations:** 6 numeric columns contain non-numeric text, following 3 patterns:
- Trailing underscores, e.g: `52312.68_`, `2_`  ==> Formatting issues (`Annual_Income`, `Num_of_Loan`, `Num_of_Delayed_Payment`, `Outstanding_Debt`)
- 1 underscore only `_`  ==> Can be placeholder for missing (`Changed_Credit_Limit`)
- Underscores before and after digits, e.g: `__10000__`, `__-333333333333333333333333333__`  ==> Sentinel values (`Amount_invested_monthly`, `Monthly_Balance`)

In [99]:
# Confirm that every non-numeric value falls into one of the 3 patterns
pattern_results = []

for column_name in numeric_columns:
    raw = F.trim(F.col(column_name))
    pattern_results.append(
        financials_df.select(
            F.lit(column_name).alias("column"),
            F.sum(F.when(raw.rlike(r"^-?\d+(\.\d+)?_+$"), 1).otherwise(0)).alias("trailing_underscore"),
            F.sum(F.when(raw.rlike(r"^_+$"), 1).otherwise(0)).alias("lone_underscore"),
            F.sum(F.when(raw.rlike(r"^__.*__$"), 1).otherwise(0)).alias("wrapped_sentinel"),
            F.sum(F.when(
                ~raw.rlike(numeric_pattern)
                & ~raw.rlike(r"^-?\d+(\.\d+)?_+$")
                & ~raw.rlike(r"^_+$")
                & ~raw.rlike(r"^__.*__$"), 1).otherwise(0)).alias("unexpected_pattern")
        ).toPandas()
    )

pattern_summary = pd.concat(pattern_results, ignore_index=True)
pattern_summary[pattern_summary.drop(columns="column").sum(axis=1) > 0]

,column,trailing_underscore,lone_underscore,wrapped_sentinel,unexpected_pattern
0,Annual_Income,859,0,0,0
5,Num_of_Loan,623,0,0,0
7,Num_of_Delayed_Payment,374,0,0,0
8,Changed_Credit_Limit,0,254,0,0
10,Outstanding_Debt,139,0,0,0
13,Amount_invested_monthly,0,0,558,0
14,Monthly_Balance,0,0,1,0

### 3. Cleaning

#### 3.1. Parse numeric columns

**Cleaning rules:**
- Trailing underscore ==> Remove underscore, keep value
- Lone underscore / wrapped sentinel ==> Convert to Null (the value carries no information)

In [100]:
def parse_numeric(column_name, target_type):
    raw = F.trim(F.col(column_name))
    is_sentinel = raw.rlike(r"^_+$") | raw.rlike(r"^__.*__$")
    normalized = F.regexp_replace(raw, r"_+$", "")
    
    # Cast via double first so integer columns stored as "3.0" parse correctly
    return F.when(is_sentinel, F.lit(None)).otherwise(normalized).cast("double").cast(target_type)


financials_parsed_df = financials_df
for column_name, target_type in numeric_columns.items():
    financials_parsed_df = financials_parsed_df.withColumn(
        column_name, parse_numeric(column_name, target_type)
    )

# Verify: nulls after parsing should only come from sentinels
parse_check = []
for column_name in numeric_columns:
    raw = F.trim(financials_df[column_name])
    parse_check.append({
        "column": column_name,
        "sentinel_rows": financials_df.filter(raw.rlike(r"^_+$") | raw.rlike(r"^__.*__$")).count(),
        "null_after_parsing": financials_parsed_df.filter(F.col(column_name).isNull()).count()
    })

parse_check_df = pd.DataFrame(parse_check)
parse_check_df["unexpected_nulls"] = parse_check_df["null_after_parsing"] - parse_check_df["sentinel_rows"]
parse_check_df

,column,sentinel_rows,null_after_parsing,unexpected_nulls
0,Annual_Income,0,0,0
1,Monthly_Inhand_Salary,0,0,0
2,Num_Bank_Accounts,0,0,0
3,Num_Credit_Card,0,0,0
4,Interest_Rate,0,0,0
5,Num_of_Loan,0,0,0
6,Delay_from_due_date,0,0,0
7,Num_of_Delayed_Payment,0,0,0
8,Changed_Credit_Limit,254,254,0
9,Num_Credit_Inquiries,0,0,0
10,Outstanding_Debt,0,0,0
11,Credit_Utilization_Ratio,0,0,0
12,Total_EMI_per_month,0,0,0
13,Amount_invested_monthly,558,558,0
14,Monthly_Balance,1,1,0

#### 3.2. Range check

##### 3.2.1. Distribution

In [101]:
count_columns = [
    "Num_Bank_Accounts", 
    "Num_Credit_Card", 
    "Interest_Rate", 
    "Num_of_Loan",
    "Delay_from_due_date", 
    "Num_of_Delayed_Payment", 
    "Num_Credit_Inquiries",
    "Changed_Credit_Limit"
]

distribution_rows = []
for column_name in count_columns:
    stats = financials_parsed_df.select(
        F.min(column_name).alias("min"),
        F.percentile_approx(column_name, 0.5).alias("p50"),
        F.percentile_approx(column_name, 0.95).alias("p95"),
        F.percentile_approx(column_name, 0.99).alias("p99"),
        F.max(column_name).alias("max"),
        F.sum(F.when(F.col(column_name) < 0, 1).otherwise(0)).alias("negative_rows")
    ).first().asDict()
    distribution_rows.append({"column": column_name, **stats})

pd.DataFrame(distribution_rows)

,column,min,p50,p95,p99,max,negative_rows
0,Num_Bank_Accounts,-1.00,6.00,10.0,511.000000,1756.000000,4
1,Num_Credit_Card,0.00,5.00,10.0,874.000000,1499.000000,0
2,Interest_Rate,1.00,14.00,33.0,2865.000000,5789.000000,0
3,Num_of_Loan,-100.00,3.00,8.0,9.000000,1495.000000,500
4,Delay_from_due_date,-5.00,18.00,54.0,61.000000,67.000000,88
5,Num_of_Delayed_Payment,-3.00,14.00,24.0,27.000000,4293.000000,84
6,Num_Credit_Inquiries,0.00,6.00,14.0,884.000000,2554.000000,0
7,Changed_Credit_Limit,-6.49,9.41,23.6,28.790001,36.970001,204

In [102]:
money_columns = [
    "Annual_Income", 
    "Monthly_Inhand_Salary", 
    "Outstanding_Debt", 
    "Total_EMI_per_month",
    "Amount_invested_monthly", 
    "Monthly_Balance", 
]

distribution2_rows = []
for column_name in money_columns:
    stats = financials_parsed_df.select(
        F.min(column_name).alias("min"),
        F.percentile_approx(column_name, 0.5).alias("p50"),
        F.percentile_approx(column_name, 0.95).alias("p95"),
        F.percentile_approx(column_name, 0.99).alias("p99"),
        F.max(column_name).alias("max"),
        F.sum(F.when(F.col(column_name) < 0, 1).otherwise(0)).alias("negative_rows")
    ).first().asDict()
    distribution2_rows.append({"column": column_name, **stats})

pd.DataFrame(distribution2_rows)

,column,min,p50,p95,p99,max,negative_rows
0,Annual_Income,7005.930176,37551.781250,134282.843750,178793.921875,2.383470e+07,0
1,Monthly_Inhand_Salary,303.645416,3085.853271,10803.636719,13788.976562,1.520463e+04,0
2,Outstanding_Debt,0.230000,1166.079956,4073.620117,4804.870117,4.998070e+03,0
3,Total_EMI_per_month,0.000000,72.876320,590.557556,57478.000000,8.197100e+04,0
4,Amount_invested_monthly,0.000000,127.332077,613.877808,1015.943848,1.977326e+03,0
5,Monthly_Balance,0.382558,339.728455,863.627319,1126.623535,1.463792e+03,0

**Observations:***
- `Num_Bank_Accounts`, `Num_Credit_Card`, `Interest_Rate`, `Num_of_Loan`, `Num_of_Delayed_Payment`, `Num_Credit_Inquiries`: p95 is small but max is in the hundreds/thousands
- Negative values in `Num_Bank_Accounts`, `Num_of_Loan` (-100) and `Num_of_Delayed_Payment` ==> A count cannot be negative

##### 3.2.2. Find natural breakpoint for count columns

In [103]:
from pyspark.sql.window import Window


def inspect_value_gaps(df, column):
    w = Window.orderBy(column)

    return (
        df
        .select(column)
        .where(F.col(column).isNotNull())
        .groupBy(column)
        .count()
        .withColumn(
            "previous_value",
            F.lag(column).over(w)
        )
        .withColumn(
            "gap",
            F.col(column) - F.col("previous_value")
        )
        .orderBy(F.col(column).asc())
    )

In [104]:
gap_columns = [
    "Num_Bank_Accounts",
    "Num_Credit_Card",
    "Interest_Rate",
    "Num_of_Loan",
    "Delay_from_due_date",
    "Num_of_Delayed_Payment",
    "Num_Credit_Inquiries",
    "Changed_Credit_Limit",
]

for column_name in gap_columns:
    print(f"Value gaps for {column_name}:")
    (
        inspect_value_gaps(financials_parsed_df, column_name)
        .filter(F.col("gap") > 1)
        .show(50, truncate=False)
    )

Value gaps for Num_Bank_Accounts:
+-----------------+-----+--------------+---+
|Num_Bank_Accounts|count|previous_value|gap|
+-----------------+-----+--------------+---+
|26               |1    |11            |15 |
|28               |1    |26            |2  |
|50               |1    |28            |22 |
|53               |1    |50            |3  |
|57               |1    |53            |4  |
|64               |1    |57            |7  |
|82               |1    |64            |18 |
|122              |1    |82            |40 |
|129              |1    |122           |7  |
|160              |1    |129           |31 |
|179              |1    |162           |17 |
|182              |1    |179           |3  |
|194              |1    |182           |12 |
|196              |1    |194           |2  |
|203              |1    |196           |7  |
|210              |1    |203           |7  |
|216              |1    |210           |6  |
|224              |1    |216           |8  |
|229              |2    |224           |5  |
|239              |1    |229           |10 |
|271              |1    |239           |32 |
|275              |1    |272           |3  |
|307              |1    |275           |32 |
|310              |1    |307           |3  |
|312              |1    |310           |2  |
|330              |1    |313           |17 |
|334              |1    |331           |3  |
|340              |1    |334           |6  |
|356              |1    |340           |16 |
|374              |1    |356           |18 |
|386              |1    |374           |12 |
|427              |1    |386           |41 |
|466              |1    |427           |39 |
|485              |1    |466           |19 |
|489              |1    |485           |4  |
|511              |1    |489           |22 |
|514              |1    |512           |2  |
|527              |1    |514           |13 |
|535              |1    |528           |7  |
|549              |1    |535           |14 |
|555              |1    |549           |6  |
|560              |2    |555           |5  |
|565              |1    |560           |5  |
|587              |1    |565           |22 |
|609              |1    |588           |21 |
|611              |1    |609           |2  |
|616              |1    |611           |5  |
|627              |1    |616           |11 |
|632              |1    |627           |5  |
|637              |1    |632           |5  |
+-----------------+-----+--------------+---+
only showing top 50 rows

Value gaps for Num_Credit_Card:
+---------------+-----+--------------+---+
|Num_Credit_Card|count|previous_value|gap|
+---------------+-----+--------------+---+
|21             |1    |11            |10 |
|25             |2    |21            |4  |
|35             |1    |25            |10 |
|38             |1    |35            |3  |
|43             |1    |38            |5  |
|48             |1    |43            |5  |
|51             |1    |48            |3  |
|54             |1    |52            |2  |
|57             |1    |54            |3  |
|62             |1    |57            |5  |
|65             |1    |62            |3  |
|70             |1    |65            |5  |
|75             |1    |71            |4  |
|77             |1    |75            |2  |
|82             |1    |77            |5  |
|86             |1    |82            |4  |
|97             |1    |86            |11 |
|100            |1    |97            |3  |
|106            |1    |100           |6  |
|110            |2    |107           |3  |
|119            |1    |110           |9  |
|126            |1    |119           |7  |
|129            |1    |126           |3  |
|131            |1    |129           |2  |
|133            |1    |131           |2  |
|147            |1    |133           |14 |
|158            |1    |148           |10 |
|169            |1    |158           |11 |
|171            |1    |169           |2  |
|180            |3    |171           |9  |
|183            |2    |180           |3  |
|191            |1    |183           |8  |
|194            |1    |192           |2  |
|199            |1    |194           |5  |
|210            |1    |201           |9  |
|212            |1    |210           |2  |
|214            |1    |212           |2  |
|219            |1    |215           |4  |
|224            |1    |219           |5  |
|232            |1    |224           |8  |
|237            |2    |232           |5  |
|249            |1    |238           |11 |
|253            |1    |249           |4  |
|259            |1    |253           |6  |
|275            |1    |259           |16 |
|284            |1    |275           |9  |
|291            |1    |284           |7  |
|294            |2    |291           |3  |
|300            |1    |294           |6  |
|303            |1    |300           |3  |
+---------------+-----+--------------+---+
only showing top 50 rows

Value gaps for Interest_Rate:
+-------------+-----+--------------+---+
|Interest_Rate|count|previous_value|gap|
+-------------+-----+--------------+---+
|99           |1    |34            |65 |
|106          |1    |101           |5  |
|115          |1    |107           |8  |
|170          |1    |115           |55 |
|207          |1    |170           |37 |
|224          |1    |207           |17 |
|262          |1    |224           |38 |
|268          |1    |262           |6  |
|279          |1    |268           |11 |
|286          |1    |279           |7  |
|288          |1    |286           |2  |
|316          |1    |288           |28 |
|318          |1    |316           |2  |
|328          |1    |318           |10 |
|332          |1    |328           |4  |
|334          |1    |332           |2  |
|348          |1    |334           |14 |
|356          |1    |348           |8  |
|377          |1    |356           |21 |
|418          |1    |377           |41 |
|422          |1    |418           |4  |
|426          |1    |422           |4  |
|443          |1    |426           |17 |
|450          |1    |443           |7  |
|482          |1    |450           |32 |
|498          |2    |482           |16 |
|504          |1    |498           |6  |
|570          |1    |504           |66 |
|608          |1    |570           |38 |
|613          |1    |608           |5  |
|629          |1    |613           |16 |
|642          |1    |629           |13 |
|648          |1    |642           |6  |
|713          |1    |648           |65 |
|718          |1    |713           |5  |
|750          |1    |718           |32 |
|754          |1    |751           |3  |
|757          |1    |754           |3  |
|774          |1    |757           |17 |
|781          |1    |774           |7  |
|816          |1    |781           |35 |
|826          |1    |816           |10 |
|835          |1    |826           |9  |
|854          |1    |835           |19 |
|870          |1    |854           |16 |
|887          |1    |870           |17 |
|917          |1    |890           |27 |
|926          |1    |917           |9  |
|935          |1    |926           |9  |
|940          |1    |935           |5  |
+-------------+-----+--------------+---+
only showing top 50 rows

Value gaps for Num_of_Loan:
+-----------+-----+--------------+---+
|Num_of_Loan|count|previous_value|gap|
+-----------+-----+--------------+---+
|0          |1363 |-100          |100|
|18         |1    |9             |9  |
|27         |1    |18            |9  |
|31         |1    |27            |4  |
|33         |1    |31            |2  |
|55         |1    |33            |22 |
|58         |1    |55            |3  |
|65         |1    |58            |7  |
|83         |1    |65            |18 |
|87         |1    |83            |4  |
|103        |1    |87            |16 |
|119        |1    |103           |16 |
|146        |1    |119           |27 |
|172        |2    |146           |26 |
|186        |1    |172           |14 |
|192        |1    |186           |6  |
|227        |1    |192           |35 |
|237        |1    |227           |10 |
|251        |1    |237           |14 |
|285        |1    |251           |34 |
|332        |1    |285           |47 |
|365        |1    |332           |33 |
|387        |1    |365           |22 |
|404        |1    |387           |17 |
|420        |1    |404           |16 |
|438        |1    |420           |18 |
|455        |1    |439           |16 |
|463        |1    |455           |8  |
|497        |1    |463           |34 |
|520        |1    |497           |23 |
|614        |1    |520           |94 |
|653        |1    |614           |39 |
|699        |1    |653           |46 |
|777        |1    |699           |78 |
|781        |1    |777           |4  |
|785        |1    |781           |4  |
|795        |1    |785           |10 |
|799        |1    |795           |4  |
|860        |1    |799           |61 |
|917        |1    |860           |57 |
|945        |1    |917           |28 |
|966        |1    |945           |21 |
|999        |1    |966           |33 |
|1014       |1    |999           |15 |
|1053       |1    |1014          |39 |
|1070       |1    |1053          |17 |
|1074       |1    |1070          |4  |
|1085       |1    |1074          |11 |
|1091       |1    |1085          |6  |
|1127       |1    |1091          |36 |
+-----------+-----+--------------+---+
only showing top 50 rows

Value gaps for Delay_from_due_date:
+-------------------+-----+--------------+---+
|Delay_from_due_date|count|previous_value|gap|
+-------------------+-----+--------------+---+
+-------------------+-----+--------------+---+

Value gaps for Num_of_Delayed_Payment:
+----------------------+-----+--------------+---+
|Num_of_Delayed_Payment|count|previous_value|gap|
+----------------------+-----+--------------+---+
|47                    |1    |28            |19 |
|88                    |1    |47            |41 |
|133                   |1    |88            |45 |
|430                   |1    |133           |297|
|450                   |1    |430           |20 |
|538                   |1    |450           |88 |
|615                   |1    |538           |77 |
|659                   |1    |615           |44 |
|662                   |1    |659           |3  |
|733                   |1    |663           |70 |
|758                   |1    |733           |25 |
|787                   |1    |758           |29 |
|813                   |1    |787           |26 |
|834                   |1    |813           |21 |
|853                   |1    |834           |19 |
|938                   |1    |853           |85 |
|960                   |1    |938           |22 |
|969                   |1    |960           |9  |
|996                   |1    |969           |27 |
|1014                  |1    |996           |18 |
|1154                  |1    |1014          |140|
|1177                  |1    |1154          |23 |
|1263                  |1    |1178          |85 |
|1473                  |1    |1263          |210|
|1509                  |1    |1473          |36 |
|1614                  |1    |1509          |105|
|1673                  |1    |1614          |59 |
|1718                  |1    |1673          |45 |
|1820                  |1    |1718          |102|
|1841                  |1    |1820          |21 |
|1850                  |1    |1841          |9  |
|1879                  |1    |1850          |29 |
|1884                  |1    |1879          |5  |
|1891                  |1    |1884          |7  |
|1975                  |1    |1891          |84 |
|1989                  |1    |1975          |14 |
|2056                  |1    |1989          |67 |
|2072                  |1    |2056          |16 |
|2080                  |1    |2072          |8  |
|2128                  |1    |2080          |48 |
|2138                  |1    |2128          |10 |
|2148                  |1    |2138          |10 |
|2222                  |1    |2148          |74 |
|2239                  |1    |2222          |17 |
|2276                  |1    |2239          |37 |
|2278                  |1    |2276          |2  |
|2323                  |1    |2278          |45 |
|2334                  |1    |2324          |10 |
|2438                  |1    |2334          |104|
|2503                  |1    |2438          |65 |
+----------------------+-----+--------------+---+
only showing top 50 rows

Value gaps for Num_Credit_Inquiries:
+--------------------+-----+--------------+---+
|Num_Credit_Inquiries|count|previous_value|gap|
+--------------------+-----+--------------+---+
|26                  |1    |17            |9  |
|31                  |1    |26            |5  |
|46                  |1    |31            |15 |
|64                  |1    |46            |18 |
|66                  |1    |64            |2  |
|78                  |1    |66            |12 |
|107                 |1    |78            |29 |
|113                 |1    |107           |6  |
|154                 |1    |113           |41 |
|159                 |1    |154           |5  |
|185                 |1    |160           |25 |
|190                 |1    |186           |4  |
|193                 |1    |190           |3  |
|199                 |1    |193           |6  |
|205                 |1    |199           |6  |
|207                 |1    |205           |2  |
|209                 |1    |207           |2  |
|225                 |1    |209           |16 |
|251                 |1    |225           |26 |
|262                 |1    |252           |10 |
|268                 |1    |262           |6  |
|272                 |1    |268           |4  |
|285                 |1    |272           |13 |
|287                 |1    |285           |2  |
|309                 |1    |287           |22 |
|318                 |1    |309           |9  |
|399                 |1    |318           |81 |
|421                 |1    |399           |22 |
|439                 |2    |421           |18 |
|446                 |1    |439           |7  |
|448                 |1    |446           |2  |
|455                 |1    |448           |7  |
|469                 |1    |455           |14 |
|477                 |1    |469           |8  |
|484                 |1    |477           |7  |
|514                 |1    |485           |29 |
|528                 |1    |515           |13 |
|562                 |1    |528           |34 |
|584                 |1    |562           |22 |
|615                 |1    |585           |30 |
|623                 |2    |615           |8  |
|626                 |1    |623           |3  |
|655                 |1    |626           |29 |
|692                 |1    |655           |37 |
|711                 |1    |692           |19 |
|716                 |1    |711           |5  |
|732                 |1    |716           |16 |
|743                 |1    |732           |11 |
|761                 |1    |743           |18 |
|777                 |1    |762           |15 |
+--------------------+-----+--------------+---+
only showing top 50 rows

Value gaps for Changed_Credit_Limit:

+--------------------+-----+--------------+---------+
|Changed_Credit_Limit|count|previous_value|gap      |
+--------------------+-----+--------------+---------+
|36.97               |1    |34.85         |2.1200027|
+--------------------+-----+--------------+---------+

**Observations**: Every count column has a dense cluster of realistic values followed by a large jump

E.g: A dense and continuous Interest Rate range of 1–34. The next observed value was 99, after which values were highly sparse, typically occurring only once. Values above 34 were therefore treated as data anomalies 

==> **Cleaning rule**: Thresholds are set as round numbers slightly above the observed cluster, so that realistic future values are not nulled by accident. Values outside the range ==> Convert to Null.

| Column | Valid range in Silver | Reason |
|---|---|---|
| `Num_Bank_Accounts` | 0 – 11 | Cluster ends at 11, next value 26; negative count impossible |
| `Num_Credit_Card` | 0 – 11 | Cluster ends at 11, next value 21 |
| `Interest_Rate` | 0 – 34 (%) | Cluster ends at 34, next value 99 |
| `Num_of_Delayed_Payment` | 0 – 28 | Cluster ends at 28, next value 47; negative count impossible |
| `Num_Credit_Inquiries` | 0 – 17 | Cluster ends at 17, next value 26 |
| `Num_of_Loan` |0-9 | Can be recovered from `Type_of_Loan` |
| `Delay_from_due_date` | Keep as observed | Negative is plausible, in a continuous range |
| `Changed_Credit_Limit` | Keep as observed | Negative is plausible, in a continuous range |

#### 3.3. String columns

In [105]:
string_cols = [
    'Customer_ID',
    'Type_of_Loan',
    'Credit_Mix',
    'Credit_History_Age',
    'Payment_of_Min_Amount',
    'Payment_Behaviour'
]

In [106]:
# Check null rows and number of distinct values for string columns
summary_exprs = []
for column_name in string_cols:
    summary_exprs.extend([
        F.sum(F.col(column_name).isNull().cast("int")).alias(
            f"{column_name}_null_rows"
        ),
        F.countDistinct(column_name).alias(
            f"{column_name}_distinct_values"
        ),
    ])

summary = financials_parsed_df.agg(*summary_exprs).first().asDict()

string_profile = pd.DataFrame([
    {
        "string_column": column_name,
        "null_rows": summary[f"{column_name}_null_rows"],
        "distinct_values": summary[f"{column_name}_distinct_values"],
    }
    for column_name in string_cols
])

string_profile

           string_column  null_rows  distinct_values
0            Customer_ID          0            12500
1           Type_of_Loan       1426             6260
2             Credit_Mix          0                4
3     Credit_History_Age          0              393
4  Payment_of_Min_Amount          0                3
5      Payment_Behaviour          0                7

**Observation:** 
- `Credit_Mix`, `Payment_of_Min_Amount`, `Payment_Behavior` has small distinct values ==> Categorical 
- `Type_of_Loan`: Missing 1426 rows ==> Cross-check with `Num_of_loan`

##### 3.3.1. Handle placeholders for Categorical columns

In [107]:
categorical_columns = [
    "Credit_Mix",
    "Payment_of_Min_Amount",
    "Payment_Behaviour"
]

for column_name in categorical_columns:
    print(f"Value counts for {column_name}:")
    (
        financials_parsed_df
        .groupBy(column_name)
        .count()
        .orderBy(F.desc("count"))
        .show(truncate=False)
    )

Value counts for Credit_Mix:
+----------+-----+
|Credit_Mix|count|
+----------+-----+
|Standard  |4497 |
|Good      |3032 |
|_         |2611 |
|Bad       |2360 |
+----------+-----+

Value counts for Payment_of_Min_Amount:
+---------------------+-----+
|Payment_of_Min_Amount|count|
+---------------------+-----+
|Yes                  |6571 |
|No                   |4491 |
|NM                   |1438 |
+---------------------+-----+

Value counts for Payment_Behaviour:
+--------------------------------+-----+
|Payment_Behaviour               |count|
+--------------------------------+-----+
|Low_spent_Small_value_payments  |3202 |
|High_spent_Medium_value_payments|2242 |
|Low_spent_Medium_value_payments |1686 |
|High_spent_Large_value_payments |1683 |
|High_spent_Small_value_payments |1389 |
|Low_spent_Large_value_payments  |1300 |
|!@9#%8                          |998  |
+--------------------------------+-----+

**Cleaning rules:**
- `Credit_Mix`: Convert __ to Null
- `Payment_of_Min_Amount`: Convert NM to Null
- `Payment_Behaviour`: Convert !@9#%8 to Null

In [108]:
categorical_placeholders = {
    "Credit_Mix": ["_"],
    "Payment_of_Min_Amount": ["NM"],
    "Payment_Behaviour": ["!@9#%8"],
}

categorical_clean_df = financials_parsed_df
for column_name, placeholders in categorical_placeholders.items():
    categorical_clean_df = categorical_clean_df.withColumn(
        column_name,
        F.when(
            F.trim(F.col(column_name)).isin(*placeholders),
            F.lit(None).cast(StringType())
        ).otherwise(F.trim(F.col(column_name)))
    )

for column_name in categorical_placeholders:
    print(
        f"{column_name} NULL count after cleaning: "
        f"{categorical_clean_df.filter(F.col(column_name).isNull()).count()}"
    )
    categorical_clean_df.groupBy(column_name).count().orderBy(F.desc("count")).show(truncate=False)

Credit_Mix NULL count after cleaning: 2611
+----------+-----+
|Credit_Mix|count|
+----------+-----+
|Standard  |4497 |
|Good      |3032 |
|NULL      |2611 |
|Bad       |2360 |
+----------+-----+

Payment_of_Min_Amount NULL count after cleaning: 1438
+---------------------+-----+
|Payment_of_Min_Amount|count|
+---------------------+-----+
|Yes                  |6571 |
|No                   |4491 |
|NULL                 |1438 |
+---------------------+-----+

Payment_Behaviour NULL count after cleaning: 998
+--------------------------------+-----+
|Payment_Behaviour               |count|
+--------------------------------+-----+
|Low_spent_Small_value_payments  |3202 |
|High_spent_Medium_value_payments|2242 |
|Low_spent_Medium_value_payments |1686 |
|High_spent_Large_value_payments |1683 |
|High_spent_Small_value_payments |1389 |
|Low_spent_Large_value_payments  |1300 |
|NULL                            |998  |
+--------------------------------+-----+

#### 3.4. Cross-columns check between `Type_of_Loan` and `Num_of_loans`

In [109]:
# Normalize values of Type_of_Loan (", and" into ","), then count the number of loan type in row
loan_check_df = (
    categorical_clean_df
    .withColumn(
        "loan_type_count",
        F.when(
            F.col("Type_of_Loan").isNull(),
            F.lit(0)
        ).otherwise(
            F.size(
                F.split(
                    F.regexp_replace(
                        F.col("Type_of_Loan"),
                        r", and ",
                        ", "
                    ),
                    r",\s*"
                )
            )
        )
    )
)

In [110]:
# Find the mismatch between Numb_of_loans and newly created `loan_type_count`

loan_mismatch_df = loan_check_df.filter(
    ~F.col("Num_of_Loan").eqNullSafe(F.col("loan_type_count"))
)

mismatch_row_count = loan_mismatch_df.count()
print(f"Number of mismatching rows: {mismatch_row_count}")

loan_mismatch_df.select(
    "Type_of_Loan",
    "Num_of_Loan",
    "loan_type_count"
).show(mismatch_row_count, truncate=False)

Number of mismatching rows: 567
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------+
|Type_of_Loan                                                                                                                                                                |Num_of_Loan|loan_type_count|
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------+
|Personal Loan, Auto Loan, and Not Specified                                                                                                                                 |119        |3              |
|Personal Loan, and Not Specified                                                                                                                                            |-100       |2              |
|Not Specified, Credit-Builder Loan, and Credit-Builder Loan                                                                                                                 |-100       |3              |
|Payday Loan, Personal Loan, Auto Loan, and Home Equity Loan                                                                                                                 |-100       |4              |
|Not Specified, Home Equity Loan, and Personal Loan                                                                                                                          |-100       |3              |
|Credit-Builder Loan, Student Loan, Auto Loan, and Home Equity Loan                                                                                                          |-100       |4              |
|Student Loan, Not Specified, and Mortgage Loan                                                                                                                              |-100       |3              |
|Mortgage Loan, and Home Equity Loan                                                                                                                                         |-100       |2              |
|NULL                                                                                                                                                                        |-100       |0              |
|NULL                                                                                                                                                                        |103        |0              |
|Auto Loan, Personal Loan, Personal Loan, Credit-Builder Loan, Credit-Builder Loan, Home Equity Loan, and Auto Loan                                                          |-100       |7              |
|Payday Loan, Credit-Builder Loan, Student Loan, Home Equity Loan, Personal Loan, Personal Loan, and Home Equity Loan                                                        |-100       |7              |
|NULL                                                                                                                                                                        |-100       |0              |
|Payday Loan, Credit-Builder Loan, Home Equity Loan, Payday Loan, Debt Consolidation Loan, and Not Specified                                                                 |-100       |6              |
|NULL                                                                                                                                                                        |-100       |0              |
|Payday Loan, Credit-Builder Loan, and Mortgage Loan                                                                                                                         |-100       |3              |
|Payday Loan, Debt Consolidation Loan, Not Specified, Student Loan, Mortgage Loan, Auto Loan, Student Loan, Auto Loan, and Not Specified                                     |-100       |9              |
|Not Specified, Payday Loan, Personal Loan, Auto Loan, and Student Loan                                                                                                      |-100       |5              |
|Home Equity Loan                                                                                                                                                            |-100       |1              |
|NULL                                                                                                                                                                        |-100       |0              |
|Payday Loan, and Personal Loan                                                                                                                                              |-100       |2              |
|Not Specified, and Credit-Builder Loan                                                                                                                                      |-100       |2              |
|Debt Consolidation Loan, Credit-Builder Loan, and Credit-Builder Loan                                                                                                       |-100       |3              |
|Home Equity Loan, Not Specified, Auto Loan, and Student Loan                                                                                                                |777        |4              |
|Debt Consolidation Loan, Personal Loan, Home Equity Loan, Auto Loan, and Student Loan                                                                                       |-100       |5              |
|Mortgage Loan, Home Equity Loan, Payday Loan, Not Specified, and Student Loan                                                                                               |-100       |5              |
|Home Equity Loan, and Mortgage Loan                                                                                                                                         |-100       |2              |
|Credit-Builder Loan, Auto Loan, Home Equity Loan, and Debt Consolidation Loan                                                                                               |-100       |4              |
|Auto Loan                                                                                                                                                                   |-100       |1              |
|NULL                                                                                                                                                                        |-100       |0              |
|Personal Loan, and Not Specified                                                                                                                                            |-100       |2              |
|NULL                                                                                                                                                                        |999        |0              |
|Student Loan, and Debt Consolidation Loan                                                                                                                                   |-100       |2              |
|Mortgage Loan, Auto Loan, Debt Consolidation Loan, and Credit-Builder Loan                                                                                                  |-100       |4              |
|Not Specified, and Debt Consolidation Loan                                                                                                                                  |-100       |2              |
|Not Specified, Not Specified, and Mortgage Loan                                                                                                                             |-100       |3              |
|Home Equity Loan, Payday Loan, and Debt Consolidation Loan                                                                                                                  |-100       |3              |
|Payday Loan, Home Equity Loan, Student Loan, and Credit-Builder Loan                                                                                                        |-100       |4              |
|Personal Loan, Personal Loan, Payday Loan, Credit-Builder Loan, Credit-Builder Loan, Student Loan, Home Equity Loan, and Payday Loan                                        |-100       |8              |
|Credit-Builder Loan, Not Specified, Personal Loan, Mortgage Loan, Not Specified, and Mortgage Loan                                                                          |-100       |6              |
|Auto Loan                                                                                                                                                                   |-100       |1              |
|Credit-Builder Loan, Payday Loan, Credit-Builder Loan, Credit-Builder Loan, Not Specified, Not Specified, Mortgage Loan, Student Loan, and Debt Consolidation Loan          |-100       |9              |
|Mortgage Loan                                                                                                                                                               |-100       |1              |
|Auto Loan, Home Equity Loan, Debt Consolidation Loan, and Student Loan                                                                                                      |-100       |4              |
|Student Loan, Not Specified, Home Equity Loan, Payday Loan, Payday Loan, Not Specified, and Personal Loan                                                                   |-100       |7              |
|Not Specified, Not Specified, Debt Consolidation Loan, Personal Loan, Credit-Builder Loan, Debt Consolidation Loan, and Student Loan                                        |-100       |7              |
|Debt Consolidation Loan, Auto Loan, and Home Equity Loan                                                                                                                    |-100       |3              |
|Personal Loan, Credit-Builder Loan, Mortgage Loan, Payday Loan, Student Loan, Mortgage Loan, Home Equity Loan, Auto Loan, and Credit-Builder Loan                           |-100       |9              |
|NULL                                                                                                                                                                        |1074       |0              |
|Mortgage Loan, and Home Equity Loan                                                                                                                                         |-100       |2              |
|Home Equity Loan, Auto Loan, Payday Loan, and Personal Loan                                                                                                                 |-100       |4              |
|NULL                                                                                                                                                                        |-100       |0              |
|Credit-Builder Loan, and Student Loan                                                                                                                                       |-100       |2              |
|Auto Loan, Debt Consolidation Loan, Home Equity Loan, and Payday Loan                                                                                                       |-100       |4              |
|Personal Loan, and Mortgage Loan                                                                                                                                            |-100       |2              |
|Student Loan, Home Equity Loan, Credit-Builder Loan, Debt Consolidation Loan, and Student Loan                                                                              |-100       |5              |
|Credit-Builder Loan                                                                                                                                                         |-100       |1              |
|Debt Consolidation Loan, Debt Consolidation Loan, Student Loan, Not Specified, and Credit-Builder Loan                                                                      |-100       |5              |
|Payday Loan, Personal Loan, Home Equity Loan, Credit-Builder Loan, Auto Loan, Home Equity Loan, and Mortgage Loan                                                           |-100       |7              |
|Debt Consolidation Loan, Not Specified, Personal Loan, Personal Loan, Personal Loan, Personal Loan, Home Equity Loan, and Debt Consolidation Loan                           |-100       |8              |
|Mortgage Loan, and Personal Loan                                                                                                                                            |-100       |2              |
|Not Specified                                                                                                                                                               |-100       |1              |
|Student Loan, Payday Loan, Not Specified, Personal Loan, Student Loan, Not Specified, Debt Consolidation Loan, and Not Specified                                            |1091       |8              |
|Auto Loan, Credit-Builder Loan, Payday Loan, Debt Consolidation Loan, and Mortgage Loan                                                                                     |-100       |5              |
|Personal Loan, Payday Loan, Personal Loan, Student Loan, Mortgage Loan, Auto Loan, Not Specified, and Payday Loan                                                           |-100       |8              |
|Not Specified, Student Loan, Home Equity Loan, Credit-Builder Loan, and Home Equity Loan                                                                                    |-100       |5              |
|Debt Consolidation Loan                                                                                                                                                     |-100       |1              |
|Auto Loan, Student Loan, Mortgage Loan, Student Loan, and Credit-Builder Loan                                                                                               |-100       |5              |
|NULL                                                                                                                                                                        |-100       |0              |
|Not Specified                                                                                                                                                               |-100       |1              |
|Mortgage Loan, Payday Loan, Mortgage Loan, Payday Loan, and Auto Loan                                                                                                       |-100       |5              |
|Student Loan, and Home Equity Loan                                                                                                                                          |-100       |2              |
|Home Equity Loan, and Student Loan                                                                                                                                          |-100       |2              |
|Student Loan, Credit-Builder Loan, Credit-Builder Loan, Home Equity Loan, and Not Specified                                                                                 |-100       |5              |
|Credit-Builder Loan, Not Specified, Not Specified, and Auto Loan                                                                                                            |-100       |4              |
|Home Equity Loan, Credit-Builder Loan, Not Specified, Not Specified, and Credit-Builder Loan                                                                                |1384       |5              |
|Debt Consolidation Loan                                                                                                                                                     |-100       |1              |
|Home Equity Loan, Personal Loan, Debt Consolidation Loan, Home Equity Loan, Personal Loan, and Credit-Builder Loan                                                          |-100       |6              |
|Student Loan                                                                                                                                                                |-100       |1              |
|Payday Loan, Credit-Builder Loan, Debt Consolidation Loan, and Debt Consolidation Loan                                                                                      |-100       |4              |
|Auto Loan                                                                                                                                                                   |-100       |1              |
|Not Specified, Debt Consolidation Loan, and Home Equity Loan                                                                                                                |-100       |3              |
|Personal Loan, Personal Loan, Not Specified, Auto Loan, and Personal Loan                                                                                                   |-100       |5              |
|Debt Consolidation Loan, Mortgage Loan, Debt Consolidation Loan, Home Equity Loan, Payday Loan, Auto Loan, Auto Loan, and Personal Loan                                     |785        |8              |
|Auto Loan, Debt Consolidation Loan, Credit-Builder Loan, Payday Loan, Personal Loan, Student Loan, Mortgage Loan, Credit-Builder Loan, and Personal Loan                    |-100       |9              |
|Home Equity Loan, and Not Specified                                                                                                                                         |-100       |2              |
|Auto Loan, Not Specified, Credit-Builder Loan, and Auto Loan                                                                                                                |-100       |4              |
|NULL                                                                                                                                                                        |-100       |0              |
|NULL                                                                                                                                                                        |-100       |0              |
|Student Loan, Mortgage Loan, and Home Equity Loan                                                                                                                           |-100       |3              |
|Not Specified, and Home Equity Loan                                                                                                                                         |-100       |2              |
|Credit-Builder Loan, Credit-Builder Loan, Home Equity Loan, Payday Loan, Mortgage Loan, Mortgage Loan, and Mortgage Loan                                                    |-100       |7              |
|Not Specified, and Auto Loan                                                                                                                                                |-100       |2              |
|Debt Consolidation Loan, Debt Consolidation Loan, Not Specified, Auto Loan, Credit-Builder Loan, and Payday Loan                                                            |-100       |6              |
|Not Specified, Mortgage Loan, Not Specified, Not Specified, Not Specified, and Payday Loan                                                                                  |-100       |6              |

**Cleaning rules**
- If `Num_of_Loan` is within reasonable range (0, 9) and match with `loan_type_count` → retain.
- If `Num_of_Loan` falls out of range (0, 9) but `loan_type_count` has data → Use `loan_type_count` data
- If `Type_of_Loan` = NULL and `Num_of_Loan` = 0 → Retain 0.
- If `Type_of_Loan` = NULL but `Num_of_Loan` falls out of range (0, 9) → Null
- If `Type_of_Loan` = NULL but `Num_of_Loan` within range (0, 9) → retain `Num_of_Loan`

In [111]:
num_of_loan = F.col("Num_of_Loan")
loan_type_count = F.col("loan_type_count")
type_of_loan = F.col("Type_of_Loan")

loan_clean_df = loan_check_df.withColumn(
    "Num_of_Loan_clean",
    # Type_of_Loan is NULL
    F.when(
        type_of_loan.isNull() & num_of_loan.between(0, 9),
        num_of_loan
    )

    # Num_of_Loan is valid and matches loan_type_count
    .when(
        type_of_loan.isNotNull()
        & num_of_loan.between(0, 9)
        & (num_of_loan == loan_type_count),
        num_of_loan
    )

    # Num_of_Loan is out of range but loan_type_count is available
    .when(
        type_of_loan.isNotNull()
        & ~num_of_loan.between(0, 9)
        & loan_type_count.isNotNull(),
        loan_type_count
    )
    # All remaining inconsistent / unusable cases
    .otherwise(
        F.lit(None).cast(IntegerType())
    )
)

#### 3.5. Cross-column check between `Annual_Income` and `Monthly_Inhand_Salary`

In [112]:
income_check_df = loan_clean_df.withColumn(
    "annual_income_to_salary_ratio",
    F.when(
        F.col("Monthly_Inhand_Salary") > 0,
        F.col("Annual_Income") /
        (F.col("Monthly_Inhand_Salary") * 12)
    )
)

income_check_df.select(
    "Annual_Income",
    "Monthly_Inhand_Salary",
    "annual_income_to_salary_ratio"
).summary(
    "min", "25%", "50%", "75%", "95%", "99%", "max"
).show()

+-------+-------------+---------------------+-----------------------------+
|summary|Annual_Income|Monthly_Inhand_Salary|annual_income_to_salary_ratio|
+-------+-------------+---------------------+-----------------------------+
|    min|      7005.93|            303.64542|           0.6741517258186552|
|    25%|     19453.05|            1624.7517|           0.9641223231228975|
|    50%|     37551.78|            3085.8533|           1.0034731712893914|
|    75%|     72690.14|             5944.243|           1.0490699620753805|
|    95%|    134282.84|            10803.637|           1.2174283443600677|
|    99%|    178793.92|            13788.977|           1.7009618557979378|
|    max|  2.3834698E7|            15204.634|            3859.589431259365|
+-------+-------------+---------------------+-----------------------------+

In [113]:
income_check_df.filter(
    F.col("annual_income_to_salary_ratio") > 1.5
).select(
    "Annual_Income",
    "Monthly_Inhand_Salary",
    "annual_income_to_salary_ratio"
).orderBy(
    "Annual_Income"
).show(120, truncate=False)

+-------------+---------------------+-----------------------------+
|Annual_Income|Monthly_Inhand_Salary|annual_income_to_salary_ratio|
+-------------+---------------------+-----------------------------+
|7039.745     |303.64542            |1.9320081100022914           |
|7046.5       |355.20834            |1.6531378299120234           |
|7080.7       |358.05832            |1.647939273886287            |
|7087.24      |361.60333            |1.633290588115089            |
|7189.54      |332.12833            |1.8039061127469345           |
|7200.86      |373.07166            |1.608462199664093            |
|7261.91      |393.15918            |1.5392217985817012           |
|7314.675     |319.55624            |1.9075085052182401           |
|7371.05      |403.25418            |1.5232430659788354           |
|7435.16      |333.59668            |1.8573226815923747           |
|7455.07      |357.25583            |1.7389662706455493           |
|7464.64      |391.05334            |1.5907122471015378           |
|7546.68      |391.89               |1.6047615176227734           |
|7558.55      |409.87918            |1.536743421225707            |
|7577.175     |332.43124            |1.8994341375524337           |
|7664.42      |382.70166            |1.6689283759455862           |
|7708.69      |379.39084            |1.6932165468367397           |
|7711.97      |395.66415            |1.6242669307049622           |
|7780.49      |368.37418            |1.7600966910574027           |
|7863.04      |405.25333            |1.616898067032642            |
|7981.345     |412.1121             |1.6139106307254878           |
|8044.13      |396.34418            |1.6913183788108972           |
|8079.46      |423.28833            |1.5906139674435587           |
|8135.92      |378.99335            |1.7889320967904712           |
|8139.495     |391.29126            |1.733468976976145            |
|8155.79      |380.64917            |1.7855002023552742           |
|8175.65      |424.30417            |1.6056975752752356           |
|8373.24      |429.77               |1.6235894871315895           |
|8400.715     |418.05957            |1.6745450170874085           |
|8495.375     |439.9479             |1.6091630164555464           |
|8572.585     |425.39584            |1.6793349254983103           |
|8578.89      |465.9075             |1.5344407489059306           |
|8627.12      |473.92667            |1.5169576058565726           |
|8630.4       |431.2                |1.667903474625117            |
|8707.38      |426.59097            |1.7009618557979378           |
|8741.32      |450.44333            |1.6171698616859205           |
|8776.715     |485.3929             |1.5068059259875248           |
|8780.975     |435.74792            |1.6792917245505414           |
|8830.81      |489.43604            |1.503568892901621            |
|8905.45      |487.12082            |1.5234841871277247           |
|8927.89      |461.99084            |1.6104016184061019           |
|8952.155     |466.0129             |1.6008418252656376           |
|9092.87      |477.73917            |1.586093864210618            |
|9126.455     |490.5379             |1.550416159980623            |
|9133.965     |494.16376            |1.5403067445462038           |
|9155.455     |470.9546             |1.6200173144015386           |
|9290.25      |478.1875             |1.61900405175794             |
|9592.415     |440.0409             |1.8165764401224473           |
|9598.38      |515.865              |1.550531641759541            |
|9603.845     |510.3204             |1.5682704502459568           |
|9754.75      |526.8958             |1.5428017871970265           |
|9869.175     |536.4313             |1.533153029942727            |
|9958.505     |531.8754             |1.5602815925186113           |
|10021.72     |501.9621             |1.6637577799358312           |
|10105.995    |552.16626            |1.525204129863159            |
|10112.045    |521.3611             |1.6162894317242607           |
|10179.645    |556.3038             |1.5248929140016159           |
|10186.535    |552.8779             |1.5353803870726155           |
|10189.235    |557.1029             |1.5241402224366154           |
|10366.83     |568.9025             |1.5185422750367132           |
|10413.6      |576.8                |1.5045076567662539           |
|10466.825    |573.12256            |1.5219003681915448           |
|11244.63     |578.62415            |1.619449339453331            |
|16381.95     |883.0801             |1.5459102182155704           |
|344983.0     |3451.8743            |8.328397973700506            |
|457224.0     |3201.4834            |11.901357982551424           |
|485755.0     |8238.57              |4.913423300146573            |
|580744.0     |2911.421             |16.6225822447404             |
|1034126.0    |8612.032             |10.006600200996637           |
|1127430.0    |4791.26              |19.609143439490445           |
|1241683.0    |8399.233             |12.319408502543402           |
|1379874.0    |1548.3008            |74.26819219658648            |
|1724659.0    |1593.0009            |90.22065907820026            |
|2351135.0    |1932.6642            |101.37711150537098           |
|2716542.0    |4456.6377            |50.795805151068336           |
|3031039.0    |3984.9617            |63.384948065652424           |
|3234780.0    |7321.9326            |36.81610116864927            |
|3544929.0    |1462.6058            |201.97564590346363           |
|3961526.0    |919.13               |359.17351223230895           |
|4020402.0    |2919.0166            |114.77615434618023           |
|4156013.0    |1504.0566            |230.266871148383             |
|4175074.0    |6889.0225            |50.50395055992806            |
|5505619.0    |1625.5979            |282.23557637143546           |
|5539643.0    |7181.34              |64.28283951335828            |
|5556554.0    |1342.6346            |344.87876722284136           |
|5651693.0    |2611.245             |180.36392430823966           |
|5691341.0    |1712.9691            |276.87506064431483           |
|5753875.0    |4022.83              |119.19210456853762           |
|6515990.0    |2210.0325            |245.6973614052866            |
|6755739.0    |1167.4292            |482.23759554476464           |
|6912531.0    |3076.9958            |187.20995847567175           |
|7749555.0    |5774.6333            |111.83328848094953           |
|7804958.0    |567.7979             |1145.5011174411836           |
|8006694.0    |379.6029             |1757.6907097678334           |
|8229642.0    |7424.5127            |92.37016597258588            |
|8493710.0    |3136.3633            |225.67831057649954           |
|8800037.0    |1509.8116            |485.7138299898785            |
|8933809.0    |6299.5034            |118.18139513108517           |
|9351702.0    |1851.335             |420.94408437323784           |
|9389456.0    |11228.895            |69.6822527354849             |
|9821410.0    |3468.5825            |235.9611715505046            |
|1.0243765E7  |1938.3033            |440.40942700506577           |
|1.0347315E7  |6872.15              |125.47401943722501           |
|1.064858E7   |1054.0758            |841.8575093395212            |
|1.0700217E7  |4640.715             |192.14383559914245           |
|1.0805206E7  |2844.2876            |316.57620788742787           |
|1.1149856E7  |1272.2391            |730.3302266690905            |
|1.1308032E7  |2836.3809            |332.231828770571             |
|1.1308893E7  |894.4404             |1053.6283006899173           |
|1.1403141E7  |1237.5266            |767.8717704342296            |
|1.1451837E7  |3323.63              |287.13177569352035           |
|1.1777816E7  |11636.443            |84.34576539132404            |
|1.1845938E7  |636.715              |1550.3977288210028           |
|1.1874543E7  |1077.1879            |918.6376104107405            |
|1.1993705E7  |1157.9025            |863.1775223276755            |
|1.2141519E7  |5030.592             |201.12807614971368           |
|1.2148578E7  |2723.326             |371.7445348507666            |
|1.2160681E7  |685.86835            |1477.5286213136053           |
|1.2399758E7  |10463.97             |98.74962958833567            |
|1.2550732E7  |4690.305             |222.9906707222025            |
+-------------+---------------------+-----------------------------+
only showing top 120 rows

**Observations:**
- For most customers, annual_income / 12 is close to the monthly_in-hand_salary (ratio ≈ 1.0), as expected (in-hand salary is after tax)
- A discontinuity between approximately 179,987 and 344,983 in `Annual_Income`. Observations above this breakpoint also showed substantial inconsistency with `Monthly_Inhand_Salary`. 114 rows have unusual high ratio (>2), and 113 of them are above 5 
==>  Values above 180,000 were treated as anomalous for this dataset ==> COnvert to Null

In [114]:
# Clean `Annual_Income`

income_clean_df = income_check_df.withColumn(
    "Annual_Income_clean",
    F.when(
        F.col("Annual_Income") <= 180000,
        F.col("Annual_Income")
    ).otherwise(
        F.lit(None).cast("double")
    )
)

income_clean_df.select(
    F.count("*").alias("total_rows"),
    F.sum(F.col("Annual_Income_clean").isNull().cast("int"))
        .alias("annual_income_nulls")
).show()

+----------+-------------------+
|total_rows|annual_income_nulls|
+----------+-------------------+
|     12500|                114|
+----------+-------------------+

#### 3.6. Cross-check between `Total_EMI_per_month` and `Monthly_inhand_salary`

In [115]:
emi_check_df = income_check_df.withColumn(
    "emi_to_salary_ratio",
    F.when(
        F.col("Monthly_Inhand_Salary") > 0,
        F.col("Total_EMI_per_month") /
        F.col("Monthly_Inhand_Salary")
    )
)

emi_check_df.select(
    "Num_of_Loan_clean",
    "Total_EMI_per_month",
    "Monthly_Inhand_Salary",
    "emi_to_salary_ratio"
).orderBy(
    F.desc("Total_EMI_per_month")
).show(50, truncate=False)

+-----------------+-------------------+---------------------+-------------------+
|Num_of_Loan_clean|Total_EMI_per_month|Monthly_Inhand_Salary|emi_to_salary_ratio|
+-----------------+-------------------+---------------------+-------------------+
|3                |81971.0            |973.9133             |84.16662701744157  |
|1                |81935.0            |8649.47              |9.472835051191383  |
|0                |81760.0            |3186.089             |25.661554697043062 |
|1                |81751.0            |3421.13              |23.895906557278312 |
|3                |81540.0            |6358.4424            |12.82389539620752  |
|2                |81257.0            |4526.4473            |17.95160646564613  |
|9                |81194.0            |4438.3076            |18.293909977211452 |
|0                |81171.0            |2011.5               |40.35346756152125  |
|2                |81125.0            |1454.46              |55.776715879967796 |
|0                |81050.0            |7185.5024            |11.279656594777801 |
|0                |80983.0            |3344.4167            |24.21438657347166  |
|4                |80975.0            |919.005              |88.111598489418    |
|4                |80832.0            |12642.97             |6.393434592362773  |
|5                |80768.0            |4939.92              |16.350062607764627 |
|3                |80311.0            |1352.0159            |59.40092999873417  |
|4                |80080.0            |6574.1265            |12.181086023860555 |
|1                |79971.0            |3515.086             |22.750795121918696 |
|8                |79792.0            |4794.32              |16.64302819284743  |
|4                |79633.0            |13760.89             |5.786907826053386  |
|7                |79403.0            |2879.1768            |27.578369332325288 |
|2                |79381.0            |4839.342             |16.403263776751665 |
|2                |79153.0            |4653.9136            |17.007836251726562 |
|0                |78575.0            |1345.2346            |58.40988544451525  |
|6                |78446.0            |6269.9927            |12.511338378912145 |
|4                |78278.0            |13214.604            |5.923598079007348  |
|6                |78239.0            |3860.2224            |20.26800314784121  |
|5                |77407.0            |2151.7024            |35.9747706127949   |
|4                |77237.0            |1732.2167            |44.58853278774071  |
|2                |77114.0            |2115.4475            |36.45280709826907  |
|1                |77033.0            |2263.08              |34.03900760940954  |
|7                |76779.0            |1077.1879            |71.27726036320293  |
|4                |76493.0            |2550.4482            |29.991982873721263 |
|4                |76419.0            |2373.9734            |32.19033556342971  |
|1                |76076.0            |3402.46              |22.359116895835072 |
|0                |75639.0            |1692.6               |44.68805452618277  |
|2                |75589.0            |9276.23              |8.148676367479887  |
|3                |75581.0            |1469.4867            |51.433606232246376 |
|6                |75563.0            |4052.8875            |18.644238437499983 |
|0                |75532.0            |4789.902             |15.769007858431012 |
|2                |74926.0            |2098.6157            |35.702582035917    |
|8                |74787.0            |4617.975             |16.19476034809206  |
|1                |74523.0            |2308.865             |32.27689809287424  |
|2                |74503.0            |12222.09             |6.095766023033986  |
|2                |74296.0            |5631.933             |13.191918051699993 |
|4                |74263.0            |9450.29              |7.858277332551281  |
|7                |73767.0            |5783.067             |12.755688520524926 |
|4                |73709.0            |1487.5642            |49.55013004132733  |
|3                |73384.0            |896.5892             |81.84796589342055  |
|2                |73367.0            |2974.4               |24.666151966381086 |
|4                |73067.0            |6841.473             |10.680009766377042 |
+-----------------+-------------------+---------------------+-------------------+
only showing top 50 rows

In [116]:
emi_check_df.filter(
    F.col("Num_of_Loan_clean") == 0
).select(
    "Num_of_Loan_clean",
    "Type_of_Loan",
    "Total_EMI_per_month"
).orderBy(
    F.desc("Total_EMI_per_month")
).show(50, truncate=False)

+-----------------+------------+-------------------+
|Num_of_Loan_clean|Type_of_Loan|Total_EMI_per_month|
+-----------------+------------+-------------------+
|0                |NULL        |81760.0            |
|0                |NULL        |81171.0            |
|0                |NULL        |81050.0            |
|0                |NULL        |80983.0            |
|0                |NULL        |78575.0            |
|0                |NULL        |75639.0            |
|0                |NULL        |75532.0            |
|0                |NULL        |70266.0            |
|0                |NULL        |68575.0            |
|0                |NULL        |66949.0            |
|0                |NULL        |66474.0            |
|0                |NULL        |66444.0            |
|0                |NULL        |66045.0            |
|0                |NULL        |64439.0            |
|0                |NULL        |62337.0            |
|0                |NULL        |60579.0            |
|0                |NULL        |59835.0            |
|0                |NULL        |59415.0            |
|0                |NULL        |56641.0            |
|0                |NULL        |56524.0            |
|0                |NULL        |54970.0            |
|0                |NULL        |52264.0            |
|0                |NULL        |48352.0            |
|0                |NULL        |47610.0            |
|0                |NULL        |45324.0            |
|0                |NULL        |42558.0            |
|0                |NULL        |42213.0            |
|0                |NULL        |41584.0            |
|0                |NULL        |39954.0            |
|0                |NULL        |33914.0            |
|0                |NULL        |33406.0            |
|0                |NULL        |28677.0            |
|0                |NULL        |27141.0            |
|0                |NULL        |26904.0            |
|0                |NULL        |26202.0            |
|0                |NULL        |24612.0            |
|0                |NULL        |20392.0            |
|0                |NULL        |20083.0            |
|0                |NULL        |16050.0            |
|0                |NULL        |12643.0            |
|0                |NULL        |12529.0            |
|0                |NULL        |12358.0            |
|0                |NULL        |12342.0            |
|0                |NULL        |11711.0            |
|0                |NULL        |11360.0            |
|0                |NULL        |9733.0             |
|0                |NULL        |9054.0             |
|0                |NULL        |8876.0             |
|0                |NULL        |7354.0             |
|0                |NULL        |5600.0             |
+-----------------+------------+-------------------+
only showing top 50 rows

In [117]:
# Check customer count with EMI > 0 while number_of_loan_clean = 0
emi_check_df.filter(
    (F.col("Num_of_Loan_clean") == 0) &
    (F.col("Total_EMI_per_month") > 0)
).count()

143

In [118]:
emi_exceeds_salary_df = emi_check_df.filter(
    F.col("Total_EMI_per_month") > F.col("Monthly_Inhand_Salary")
)

print(f"Rows where EMI exceeds monthly in-hand salary: {emi_exceeds_salary_df.count()}")

emi_exceeds_salary_df.select(
    "Customer_ID",
    "Total_EMI_per_month",
    "Monthly_Inhand_Salary",
    "Num_of_Loan_clean",
    "snapshot_date"
).show(truncate=False)

Rows where EMI exceeds monthly in-hand salary: 397
+-----------+-------------------+---------------------+-----------------+-------------+
|Customer_ID|Total_EMI_per_month|Monthly_Inhand_Salary|Num_of_Loan_clean|snapshot_date|
+-----------+-------------------+---------------------+-----------------+-------------+
|CUS_0x12fb |57567.0            |1949.2426            |1                |2023-01-01   |
|CUS_0x16f4 |52215.0            |2592.5808            |3                |2023-01-01   |
|CUS_0x2baf |80768.0            |4939.92              |5                |2023-01-01   |
|CUS_0x3433 |7354.0             |1366.2312            |0                |2023-01-01   |
|CUS_0x36b3 |17653.0            |1228.6438            |4                |2023-01-01   |
|CUS_0x3e6d |22409.0            |9270.065             |4                |2023-01-01   |
|CUS_0x48ae |74503.0            |12222.09             |2                |2023-01-01   |
|CUS_0x553e |70266.0            |9276.62              |0                |2023-01-01   |
|CUS_0x635a |19559.0            |3043.01              |1                |2023-01-01   |
|CUS_0x63d  |31546.0            |1888.5125            |7                |2023-01-01   |
|CUS_0x7c58 |16040.0            |4302.0376            |6                |2023-01-01   |
|CUS_0x97bd |32292.0            |639.0158             |3                |2023-01-01   |
|CUS_0xb437 |59415.0            |4996.485             |0                |2023-01-01   |
|CUS_0xb51c |5032.0             |1369.815             |4                |2023-01-01   |
|CUS_0xbca6 |13431.0            |2807.6284            |9                |2023-01-01   |
|CUS_0xc5cb |70749.0            |2780.78              |3                |2023-01-01   |
|CUS_0xe84  |58181.0            |1613.0564            |9                |2023-01-01   |
|CUS_0xe98  |21656.0            |5622.348             |3                |2023-01-01   |
|CUS_0x185e |46681.0            |1788.0658            |3                |2023-02-01   |
|CUS_0x3cc2 |81760.0            |3186.089             |0                |2023-02-01   |
+-----------+-------------------+---------------------+-----------------+-------------+
only showing top 20 rows

In [119]:
emi = F.col("Total_EMI_per_month")
salary = F.col("Monthly_Inhand_Salary")

whole_emi_df = emi_check_df.filter(
    (emi > 0) & (emi == F.floor(emi))
)

whole_emi_df.agg(
    F.sum(
        F.when(emi < salary, 1).otherwise(0)
    ).alias("emi_below_salary"),
    F.sum(
        F.when(emi > salary, 1).otherwise(0)
    ).alias("emi_above_salary")
).show()

# Num_of_Loan_clean values for rows where whole-number EMI is below salary
(
    whole_emi_df
    .filter(emi < salary)
    .groupBy("Num_of_Loan_clean")
    .count()
    .orderBy("Num_of_Loan_clean")
    .show()
)

+----------------+----------------+
|emi_below_salary|emi_above_salary|
+----------------+----------------+
|              15|             397|
+----------------+----------------+

+-----------------+-----+
|Num_of_Loan_clean|count|
+-----------------+-----+
|                0|    4|
|                1|    1|
|                2|    5|
|                3|    1|
|                4|    1|
|                6|    1|
|                7|    2|
+-----------------+-----+

**Observations:**
- 143 customers without loans have positive EMI ==> Not plausible
- 397 Monthly EMI larger than the monthly in-hand salary ==> not realistic for a repayment obligation. These EMI values are also in whole number while most other EMI in double format
- 15 rows with EMI as a positive whole number, 4 of which has num_of_loan_clean = 0

==> **Cleaning rules:** 
- EMI < 0 → NULL
- EMI > 0 and Num_of_Loan_clean = 0 → NULL
- EMI is whole number and EMI > Monthly_Inhand_Salary → NULL
- Otherwise → retain

In [120]:
emi = F.col("Total_EMI_per_month")
salary = F.col("Monthly_Inhand_Salary")
num_loans = F.col("Num_of_Loan_clean")

emi_clean_df = (
    emi_check_df
    .withColumn(
        "Total_EMI_per_month_clean",
        F.when(
            emi < 0,
            F.lit(None).cast("double")
        )
        .when(
            (num_loans == 0) & (emi > 0),
            F.lit(None).cast("double")
        )
        .when(
            (emi > 0)
            & (emi == F.floor(emi))
            & (emi > salary),
            F.lit(None).cast("double")
        )
        .otherwise(emi)
    )
)

#### 3.7. Parse `Credit_History_Age` to months

COnvert `Credit_History_Age` from text to number of months: 

E.g: "16 Years and 2 Months" → 16 × 12 + 2 = 194 months

In [121]:
history_years = F.regexp_extract(F.col("Credit_History_Age"), r"(\d+)\s+Years?", 1)
history_months = F.regexp_extract(F.col("Credit_History_Age"), r"(\d+)\s+Months?", 1)

history_clean_df = emi_clean_df.withColumn(
    "credit_history_age_months",
    F.when(
        (history_years == "") | (history_months == ""),
        F.lit(None).cast(IntegerType())
    ).otherwise(
        (history_years.cast(IntegerType()) * 12 + history_months.cast(IntegerType())).cast(IntegerType())
    )
)

history_clean_df.select("Credit_History_Age", "credit_history_age_months").show(5, truncate=False)
history_clean_df.select(
    F.min("credit_history_age_months").alias("min_months"),
    F.max("credit_history_age_months").alias("max_months"),
    F.sum(F.when(F.col("credit_history_age_months").isNull(), 1).otherwise(0)).alias("null_months")
).show()

+---------------------+-------------------------+
|Credit_History_Age   |credit_history_age_months|
+---------------------+-------------------------+
|19 Years and 9 Months|237                      |
|30 Years and 8 Months|368                      |
|15 Years and 9 Months|189                      |
|32 Years and 8 Months|392                      |
|13 Years and 8 Months|164                      |
+---------------------+-------------------------+
only showing top 5 rows

+----------+----------+-----------+
|min_months|max_months|null_months|
+----------+----------+-----------+
|         8|       404|          0|
+----------+----------+-----------+

In [122]:
history_col = F.col("Credit_History_Age")
years = F.regexp_extract(
    history_col,
    r"(\d+)\s+Years?",
    1
).cast("int")

months = F.regexp_extract(
    history_col,
    r"(\d+)\s+Months?",
    1
).cast("int")

history_clean_df = emi_clean_df.withColumn(
    "credit_history_age_months",
    F.when(
        history_col.rlike(
            r"^\s*\d+\s+Years?\s+and\s+\d+\s+Months?\s*$"
        ),
        years * 12 + months
    ).otherwise(
        F.lit(None).cast("int")
    )
)

history_clean_df.select(
    "Credit_History_Age",
    "credit_history_age_months"
).show(10, truncate=False)

+---------------------+-------------------------+
|Credit_History_Age   |credit_history_age_months|
+---------------------+-------------------------+
|19 Years and 9 Months|237                      |
|30 Years and 8 Months|368                      |
|15 Years and 9 Months|189                      |
|32 Years and 8 Months|392                      |
|13 Years and 8 Months|164                      |
|22 Years and 0 Months|264                      |
|9 Years and 9 Months |117                      |
|21 Years and 4 Months|256                      |
|15 Years and 4 Months|184                      |
|33 Years and 5 Months|401                      |
+---------------------+-------------------------+
only showing top 10 rows

#### 3.8. Apply cleaning rules in Range Check (3.2) to the remaining columns

| Column | Valid range in Silver | Reason |
|---|---|---|
| `Num_Bank_Accounts` | 0 – 11 | Cluster ends at 11, next value 26; negative count impossible |
| `Num_Credit_Card` | 0 – 11 | Cluster ends at 11, next value 21 |
| `Interest_Rate` | 0 – 34 (%) | Cluster ends at 34, next value 99 |
| `Num_of_Delayed_Payment` | 0 – 28 | Cluster ends at 28, next value 47; negative count impossible |
| `Num_Credit_Inquiries` | 0 – 17 | Cluster ends at 17, next value 26 |
| `Delay_from_due_date` | Keep as observed | Negative is plausible, in a continuous range |
| `Changed_Credit_Limit` | Keep as observed | Negative is plausible, in a continuous range |

In [123]:
range_rules = {
    "Num_Bank_Accounts": (0, 11),
    "Num_Credit_Card": (0, 11),
    "Interest_Rate": (1, 34),
    "Num_of_Delayed_Payment": (0, 28),
    "Num_Credit_Inquiries": (0, 17)
}

numeric_clean_df = history_clean_df

for column, (lower, upper) in range_rules.items():
    numeric_clean_df = numeric_clean_df.withColumn(
        f"{column}_clean",
        F.when(
            F.col(column).between(lower, upper),
            F.col(column)
        ).otherwise(
            F.lit(None).cast(numeric_clean_df.schema[column].dataType)
        )
    )

for column in range_rules.keys():

    clean_col = f"{column}_clean"

    changed_rows = numeric_clean_df.filter(
        ~F.col(column).eqNullSafe(F.col(clean_col))
    ).count()

    print(f"{column}: {changed_rows} rows cleaned")

Num_Bank_Accounts: 171 rows cleaned
Num_Credit_Card: 296 rows cleaned
Interest_Rate: 270 rows cleaned
Num_of_Delayed_Payment: 189 rows cleaned
Num_Credit_Inquiries: 195 rows cleaned

In [124]:
financials_silver_df = numeric_clean_df.select(
    F.col("Customer_ID").alias("customer_id"),

    F.when(
        F.col("Annual_Income") <= 180000,
        F.col("Annual_Income")
    ).otherwise(
        F.lit(None).cast("double")
    ).alias("annual_income"),

    F.col("Monthly_Inhand_Salary")
        .cast("double")
        .alias("monthly_inhand_salary"),

    F.col("Num_Bank_Accounts_clean")
        .cast("int")
        .alias("num_bank_accounts"),

    F.col("Num_Credit_Card_clean")
        .cast("int")
        .alias("num_credit_card"),

    F.col("Interest_Rate_clean")
        .cast("int")
        .alias("interest_rate"),

    F.col("Num_of_Loan_clean")
        .cast("int")
        .alias("num_of_loan"),

    F.col("Type_of_Loan")
        .alias("type_of_loan"),

    F.col("Delay_from_due_date")
        .cast("int")
        .alias("delay_from_due_date"),

    F.col("Num_of_Delayed_Payment_clean")
        .cast("int")
        .alias("num_of_delayed_payment"),

    F.col("Changed_Credit_Limit")
        .cast("double")
        .alias("changed_credit_limit"),

    F.col("Num_Credit_Inquiries_clean")
        .cast("int")
        .alias("num_credit_inquiries"),

    F.col("Credit_Mix")
        .alias("credit_mix"),

    F.col("Outstanding_Debt")
        .cast("double")
        .alias("outstanding_debt"),

    F.col("Credit_Utilization_Ratio")
        .cast("double")
        .alias("credit_utilization_ratio"),

    F.col("credit_history_age_months")
        .cast("int")
        .alias("credit_history_age_months"),

    F.col("Payment_of_Min_Amount")
        .alias("payment_of_min_amount"),

    F.col("Total_EMI_per_month_clean")
        .cast("double")
        .alias("total_emi_per_month"),

    F.col("Amount_invested_monthly")
        .cast("double")
        .alias("amount_invested_monthly"),

    F.col("Payment_Behaviour")
        .alias("payment_behaviour"),

    F.col("Monthly_Balance")
        .cast("double")
        .alias("monthly_balance"),

    F.to_date("snapshot_date")
        .alias("snapshot_date")
)

## Build Silver Table for `Features_financials`

In [135]:
bronze_directory = "datamart/bronze/financials"
silver_directory = "datamart/silver/financials"

for snapshot_date in date_str_lst:
    utils.data_processing_silver_table.process_feature_financials_silver_table(
        snapshot_date,
        bronze_directory,
        silver_directory,
        spark
    )

loaded from: datamart/bronze/financials/bronze_feature_financials_2023_01_01.csv row count: 530

saved to: datamart/silver/financials/silver_feature_financials_2023_01_01.parquet row count: 530
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_02_01.csv row count: 501
saved to: datamart/silver/financials/silver_feature_financials_2023_02_01.parquet row count: 501
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_03_01.csv row count: 506
saved to: datamart/silver/financials/silver_feature_financials_2023_03_01.parquet row count: 506
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_04_01.csv row count: 510
saved to: datamart/silver/financials/silver_feature_financials_2023_04_01.parquet row count: 510
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_05_01.csv row count: 521
saved to: datamart/silver/financials/silver_feature_financials_2023_05_01.parquet row count: 521
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_06_01.csv row count: 517
saved to: datamart/silver/financials/silver_feature_financials_2023_06_01.parquet row count: 517
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_07_01.csv row count: 471
saved to: datamart/silver/financials/silver_feature_financials_2023_07_01.parquet row count: 471
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_08_01.csv row count: 481
saved to: datamart/silver/financials/silver_feature_financials_2023_08_01.parquet row count: 481
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_09_01.csv row count: 454
saved to: datamart/silver/financials/silver_feature_financials_2023_09_01.parquet row count: 454
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_10_01.csv row count: 487
saved to: datamart/silver/financials/silver_feature_financials_2023_10_01.parquet row count: 487
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_11_01.csv row count: 491
saved to: datamart/silver/financials/silver_feature_financials_2023_11_01.parquet row count: 491
loaded from: datamart/bronze/financials/bronze_feature_financials_2023_12_01.csv row count: 489
saved to: datamart/silver/financials/silver_feature_financials_2023_12_01.parquet row count: 489
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_01_01.csv row count: 485

saved to: datamart/silver/financials/silver_feature_financials_2024_01_01.parquet row count: 485
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_02_01.csv row count: 518

saved to: datamart/silver/financials/silver_feature_financials_2024_02_01.parquet row count: 518
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_03_01.csv row count: 511
saved to: datamart/silver/financials/silver_feature_financials_2024_03_01.parquet row count: 511
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_04_01.csv row count: 513
saved to: datamart/silver/financials/silver_feature_financials_2024_04_01.parquet row count: 513
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_05_01.csv row count: 491
saved to: datamart/silver/financials/silver_feature_financials_2024_05_01.parquet row count: 491
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_06_01.csv row count: 498
saved to: datamart/silver/financials/silver_feature_financials_2024_06_01.parquet row count: 498
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_07_01.csv row count: 505

saved to: datamart/silver/financials/silver_feature_financials_2024_07_01.parquet row count: 505
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_08_01.csv row count: 543
saved to: datamart/silver/financials/silver_feature_financials_2024_08_01.parquet row count: 543
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_09_01.csv row count: 493
saved to: datamart/silver/financials/silver_feature_financials_2024_09_01.parquet row count: 493
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_10_01.csv row count: 456
saved to: datamart/silver/financials/silver_feature_financials_2024_10_01.parquet row count: 456
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_11_01.csv row count: 488
saved to: datamart/silver/financials/silver_feature_financials_2024_11_01.parquet row count: 488
loaded from: datamart/bronze/financials/bronze_feature_financials_2024_12_01.csv row count: 515
saved to: datamart/silver/financials/silver_feature_financials_2024_12_01.parquet row count: 515
loaded from: datamart/bronze/financials/bronze_feature_financials_2025_01_01.csv row count: 526
saved to: datamart/silver/financials/silver_feature_financials_2025_01_01.parquet row count: 526

## EDA & Silver Preparation for `features_clickstream`

### Exploration at file-level

In [ ]:
# Explore data at file-level
clickstream_dir = "datamart/bronze/clickstream"
clickstream_files = sorted(glob.glob(os.path.join(clickstream_dir, "*.csv")))

FEATURE_COLS = [f"fe_{i}" for i in range(1, 21)]
BUSINESS_KEY = ["Customer_ID", "snapshot_date"]

results = []

for file_path in clickstream_files:
    file_name = os.path.basename(file_path)

    # Expected Bronze naming: bronze_feature_clickstream_YYYY_MM_DD.csv
    snapshot_date = file_name.replace("bronze_feature_clickstream_", "").replace(".csv", "")

    # Read Bronze consistently as strings; type casting will be enforced in Silver
    df = spark.read.csv(file_path, header=True, inferSchema=False)

    row_count = df.count()
    column_count = len(df.columns)
    distinct_customer_count = df.select("customer_id").distinct().count()

    results.append({
        "snapshot_date": snapshot_date,
        "row_number": row_count,
        "column_number": column_count,
        "distinct_customer_id": distinct_customer_count,
        "customer_id_unique_within_snapshot": (
            row_count == distinct_customer_count
        )
    })

clickstream_summary = pd.DataFrame(results).sort_values("snapshot_date")
clickstream_summary

,snapshot_date,row_number,column_number,distinct_customer_id,customer_id_unique_within_snapshot
0,2023_01_01,8974,22,8974,True
1,2023_02_01,8974,22,8974,True
2,2023_03_01,8974,22,8974,True
3,2023_04_01,8974,22,8974,True
4,2023_05_01,8974,22,8974,True
5,2023_06_01,8974,22,8974,True
6,2023_07_01,8974,22,8974,True
7,2023_08_01,8974,22,8974,True
8,2023_09_01,8974,22,8974,True
9,2023_10_01,8974,22,8974,True
10,2023_11_01,8974,22,8974,True
11,2023_12_01,8974,22,8974,True
12,2024_01_01,8974,22,8974,True
13,2024_02_01,8974,22,8974,True
14,2024_03_01,8974,22,8974,True
15,2024_04_01,8974,22,8974,True
16,2024_05_01,8974,22,8974,True
17,2024_06_01,8974,22,8974,True
18,2024_07_01,8974,22,8974,True
19,2024_08_01,8974,22,8974,True
20,2024_09_01,8974,22,8974,True
21,2024_10_01,8974,22,8974,True
22,2024_11_01,8974,22,8974,True
23,2024_12_01,8974,22,8974,True
24,2025_01_01,0,22,0,True

### Exploration at union-level

In [138]:
# Union all partitions into one dataframe
clickstream_dfs = [
    spark.read.csv(file_path, header=True, inferSchema=False)
    for file_path in clickstream_files
]

clickstream_df = clickstream_dfs[0]
for partition_df in clickstream_dfs[1:]:
    clickstream_df = clickstream_df.unionByName(partition_df)

print(f"Total rows: {clickstream_df.count()}")
clickstream_df.printSchema()
clickstream_df.show(5, truncate=False)

Total rows: 215376
root
 |-- fe_1: string (nullable = true)
 |-- fe_2: string (nullable = true)
 |-- fe_3: string (nullable = true)
 |-- fe_4: string (nullable = true)
 |-- fe_5: string (nullable = true)
 |-- fe_6: string (nullable = true)
 |-- fe_7: string (nullable = true)
 |-- fe_8: string (nullable = true)
 |-- fe_9: string (nullable = true)
 |-- fe_10: string (nullable = true)
 |-- fe_11: string (nullable = true)
 |-- fe_12: string (nullable = true)
 |-- fe_13: string (nullable = true)
 |-- fe_14: string (nullable = true)
 |-- fe_15: string (nullable = true)
 |-- fe_16: string (nullable = true)
 |-- fe_17: string (nullable = true)
 |-- fe_18: string (nullable = true)
 |-- fe_19: string (nullable = true)
 |-- fe_20: string (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- snapshot_date: string (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|63  |118 |80  |121 |55  |193 |111 |112 |-101|83   |164  |105  |-16  |-81  |-126 |114  |35   |85   |-73  |76   |CUS_0x1037 |2023-01-01   |
|-108|182 |123 |4   |-56 |27  |25  |-6  |284 |222  |203  |190  |-14  |-96  |200  |35   |130  |94   |111  |75   |CUS_0x1069 |2023-01-01   |
|-13 |8   |87  |166 |214 |-98 |215 |152 |129 |139  |14   |203  |26   |86   |171  |125  |-130 |354  |17   |302  |CUS_0x114a |2023-01-01   |
|-85 |45  |200 |89  |128 |54  |76  |51  |61  |139  |6    |197  |172  |96   |174  |163  |37   |207  |180  |118  |CUS_0x1184 |2023-01-01   |
|55  |120 |226 |-86 |253 |97  |107 |68  |103 |126  |34   |12   |76   |43   |183  |159  |-26  |104  |118  |184  |CUS_0x1297 |2023-01-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 5 rows

#### Check duplicates

In [140]:
# Number of exact duplicate rows (excluding the first occurrence)
exact_duplicate_rows = (
    clickstream_df.groupBy(clickstream_df.columns)
    .count()
    .filter(F.col("count") > 1)
    .select(F.sum(F.col("count") - 1).alias("duplicate_rows"))
    .first()["duplicate_rows"] or 0
)

# Number of duplicated (snapshot_date, customer_id) pairs
duplicated_pairs = (
    clickstream_df.groupBy("snapshot_date", "Customer_ID")
    .count()
    .filter(F.col("count") > 1)
    .count()
)

null_customer_id = clickstream_df.filter(F.col("Customer_ID").isNull()).count()
null_snapshot_date = clickstream_df.filter(F.col("snapshot_date").isNull()).count()

print(f"Number of exact duplicated rows: {exact_duplicate_rows}")
print(f"Number of duplicated (snapshot_date, customer_id) pairs: {duplicated_pairs}")
print(f"Null Customer_ID: {null_customer_id}")
print(f"Null snapshot_date: {null_snapshot_date}")

Number of exact duplicated rows: 0
Number of duplicated (snapshot_date, customer_id) pairs: 0
Null Customer_ID: 0
Null snapshot_date: 0

#### Check missing, blank

In [141]:
# Values treated as missing, regardless of letter case
missing_values = ("", "unknown", "n/a", "na", "nan", "null", "none")

missing_count_expressions = []

for column_name in clickstream_df.columns:
    column_text = F.lower(
        F.trim(F.col(column_name).cast("string"))
    )
    is_missing = (
        F.col(column_name).isNull()
        | column_text.isin(*missing_values)
    )

    missing_count_expressions.append(
        F.sum(F.when(is_missing, 1).otherwise(0)).alias(column_name)
    )

clickstream_df.select(*missing_count_expressions).show(truncate=False)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|0   |0   |0   |0   |0   |0   |0   |0   |0   |0    |0    |0    |0    |0    |0    |0    |0    |0    |0    |0    |0          |0            |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+

### Numeric Parsing check

In [144]:
numeric_parse_summary = []

for column_name in FEATURE_COLS:
    raw_value = F.trim(F.col(column_name).cast("string"))
    parsed_value = F.expr(
        f"try_cast(trim(`{column_name}`) as double)"
    )

    stats = clickstream_df.select(
        F.sum(
            F.when(
                raw_value.isNotNull()
                & (raw_value != "")
                & parsed_value.isNull(),
                1
            ).otherwise(0)
        ).alias("non_numeric_count"),
        F.min(parsed_value).alias("min"),
        F.percentile_approx(parsed_value, 0.01).alias("p01"),
        F.percentile_approx(parsed_value, 0.50).alias("median"),
        F.percentile_approx(parsed_value, 0.99).alias("p99"),
        F.max(parsed_value).alias("max"),
        F.sum(F.when(parsed_value < 0, 1).otherwise(0)).alias("negative_count"),
        F.sum(F.when(parsed_value == 0, 1).otherwise(0)).alias("zero_count"),
        F.countDistinct(parsed_value).alias("n_unique"),
    ).first().asDict()

    numeric_parse_summary.append({"column": column_name, **stats})

numeric_parse_summary = pd.DataFrame(numeric_parse_summary)
numeric_parse_summary

,column,non_numeric_count,min,p01,median,p99,max,negative_count,zero_count,n_unique
0,fe_1,0,-378.0,-130.0,101.0,334.0,541.0,33159,514,763
1,fe_2,0,-356.0,-129.0,103.0,335.0,560.0,32170,528,760
2,fe_3,0,-399.0,-130.0,104.0,338.0,583.0,32079,475,766
3,fe_4,0,-307.0,-129.0,106.0,338.0,562.0,31150,502,764
4,fe_5,0,-343.0,-129.0,107.0,341.0,570.0,30734,479,764
5,fe_6,0,-321.0,-130.0,103.0,337.0,565.0,32353,520,755
6,fe_7,0,-368.0,-126.0,107.0,340.0,537.0,30479,483,778
7,fe_8,0,-361.0,-123.0,111.0,343.0,573.0,28891,485,768
8,fe_9,0,-328.0,-119.0,115.0,347.0,577.0,27224,461,756
9,fe_10,0,-317.0,-116.0,118.0,353.0,537.0,25995,426,773
10,fe_11,0,-375.0,-134.0,100.0,334.0,613.0,34235,500,770
11,fe_12,0,-344.0,-135.0,100.0,333.0,550.0,34194,538,762
12,fe_13,0,-355.0,-134.0,101.0,335.0,530.0,34137,517,777
13,fe_14,0,-394.0,-134.0,100.0,335.0,583.0,34541,499,775
14,fe_15,0,-351.0,-135.0,100.0,334.0,597.0,34778,542,777
15,fe_16,0,-342.0,-135.0,100.0,335.0,554.0,34318,542,765
16,fe_17,0,-329.0,-136.0,100.0,335.0,516.0,34460,531,769
17,fe_18,0,-344.0,-138.0,100.0,336.0,551.0,34733,505,776
18,fe_19,0,-401.0,-139.0,100.0,338.0,560.0,34918,543,783
19,fe_20,0,-354.0,-142.0,100.0,340.0,547.0,35829,551,786

**Observations:**
- All values parsed cleanly
- Many negative values but features are anonymised without business interpretation ==> Retain original values

In [147]:
clickstream_silver_df = clickstream_df

for column_name in FEATURE_COLS:
    clickstream_silver_df = clickstream_silver_df.withColumn(
        column_name,
        F.expr(f"try_cast(trim(`{column_name}`) as int)")
    )

clickstream_silver_df = (
    clickstream_silver_df
    .withColumn(
        "customer_id",
        F.trim(F.col("Customer_ID").cast("string"))
    )
    .withColumn(
        "snapshot_date",
        F.to_date(F.trim(F.col("snapshot_date")))
    )
    .select(
        *FEATURE_COLS,
        "customer_id",
        "snapshot_date"
    )
)

clickstream_silver_df.printSchema()
clickstream_silver_df.show(5, truncate=False)

root
 |-- fe_1: integer (nullable = true)
 |-- fe_2: integer (nullable = true)
 |-- fe_3: integer (nullable = true)
 |-- fe_4: integer (nullable = true)
 |-- fe_5: integer (nullable = true)
 |-- fe_6: integer (nullable = true)
 |-- fe_7: integer (nullable = true)
 |-- fe_8: integer (nullable = true)
 |-- fe_9: integer (nullable = true)
 |-- fe_10: integer (nullable = true)
 |-- fe_11: integer (nullable = true)
 |-- fe_12: integer (nullable = true)
 |-- fe_13: integer (nullable = true)
 |-- fe_14: integer (nullable = true)
 |-- fe_15: integer (nullable = true)
 |-- fe_16: integer (nullable = true)
 |-- fe_17: integer (nullable = true)
 |-- fe_18: integer (nullable = true)
 |-- fe_19: integer (nullable = true)
 |-- fe_20: integer (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- snapshot_date: date (nullable = true)

+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|customer_id|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|63  |118 |80  |121 |55  |193 |111 |112 |-101|83   |164  |105  |-16  |-81  |-126 |114  |35   |85   |-73  |76   |CUS_0x1037 |2023-01-01   |
|-108|182 |123 |4   |-56 |27  |25  |-6  |284 |222  |203  |190  |-14  |-96  |200  |35   |130  |94   |111  |75   |CUS_0x1069 |2023-01-01   |
|-13 |8   |87  |166 |214 |-98 |215 |152 |129 |139  |14   |203  |26   |86   |171  |125  |-130 |354  |17   |302  |CUS_0x114a |2023-01-01   |
|-85 |45  |200 |89  |128 |54  |76  |51  |61  |139  |6    |197  |172  |96   |174  |163  |37   |207  |180  |118  |CUS_0x1184 |2023-01-01   |
|55  |120 |226 |-86 |253 |97  |107 |68  |103 |126  |34   |12   |76   |43   |183  |159  |-26  |104  |118  |184  |CUS_0x1297 |2023-01-01   |
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 5 rows

In [148]:
# Correlation among numeric clickstream feature columns
numeric_cols = [c for c in clickstream_silver_df.columns if c.startswith("fe_")]

# Convert to pandas for correlation analysis
feature_corr_df = clickstream_silver_df.select(*numeric_cols).toPandas().corr(method="pearson").round(4)

print("Pairwise correlation matrix:")
display(feature_corr_df)

# Top absolute correlations (excluding self-correlations)
corr_long = (
    feature_corr_df
    .stack()
    .reset_index()
    .rename(columns={"level_0": "col_a", "level_1": "col_b", 0: "corr"})
)

corr_long = corr_long[corr_long["col_a"] != corr_long["col_b"]]
corr_long["abs_corr"] = corr_long["corr"].abs()

top_corr = (
    corr_long
    .sort_values("abs_corr", ascending=False)
    .head(20)
    [["col_a", "col_b", "corr", "abs_corr"]]
)

print("\nTop absolute correlations:")
display(top_corr)

Pairwise correlation matrix:

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,fe_11,fe_12,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20
fe_1,1.0000,-0.0038,-0.0009,0.0017,0.0027,-0.0043,-0.0019,-0.0007,-0.0048,-0.0023,-0.0013,-0.0032,0.0003,-0.0000,-0.0023,0.0018,0.0025,-0.0023,-0.0010,0.0011
fe_2,-0.0038,1.0000,0.0013,0.0045,0.0059,-0.0014,-0.0049,-0.0044,-0.0043,-0.0056,-0.0002,0.0008,-0.0040,0.0033,-0.0014,-0.0035,-0.0002,-0.0004,0.0001,-0.0002
fe_3,-0.0009,0.0013,1.0000,0.0078,0.0064,-0.0037,-0.0056,-0.0097,-0.0056,-0.0082,-0.0030,0.0010,0.0004,-0.0036,-0.0019,0.0026,0.0011,0.0004,0.0015,0.0011
fe_4,0.0017,0.0045,0.0078,1.0000,0.0076,-0.0022,-0.0029,-0.0069,-0.0095,-0.0112,-0.0007,0.0004,-0.0011,-0.0021,-0.0015,-0.0011,-0.0017,-0.0007,0.0010,0.0011
fe_5,0.0027,0.0059,0.0064,0.0076,1.0000,-0.0006,-0.0018,-0.0070,-0.0123,-0.0143,0.0031,0.0006,0.0016,-0.0001,0.0024,0.0010,-0.0010,0.0008,-0.0003,0.0021
fe_6,-0.0043,-0.0014,-0.0037,-0.0022,-0.0006,1.0000,0.0003,0.0010,-0.0013,0.0055,-0.0013,0.0034,-0.0009,-0.0030,0.0013,0.0020,0.0025,-0.0009,0.0046,0.0020
fe_7,-0.0019,-0.0049,-0.0056,-0.0029,-0.0018,0.0003,1.0000,0.0019,0.0020,0.0051,0.0029,-0.0015,0.0001,0.0001,-0.0059,0.0020,0.0048,0.0016,-0.0009,0.0012
fe_8,-0.0007,-0.0044,-0.0097,-0.0069,-0.0070,0.0010,0.0019,1.0000,0.0072,0.0071,0.0024,-0.0014,-0.0027,-0.0050,0.0045,-0.0001,-0.0027,0.0030,-0.0031,0.0009
fe_9,-0.0048,-0.0043,-0.0056,-0.0095,-0.0123,-0.0013,0.0020,0.0072,1.0000,0.0059,0.0008,0.0020,-0.0012,0.0013,-0.0005,0.0009,0.0013,0.0014,0.0017,0.0001
fe_10,-0.0023,-0.0056,-0.0082,-0.0112,-0.0143,0.0055,0.0051,0.0071,0.0059,1.0000,0.0030,-0.0061,-0.0009,-0.0019,0.0032,-0.0016,0.0013,-0.0007,-0.0018,0.0009
fe_11,-0.0013,-0.0002,-0.0030,-0.0007,0.0031,-0.0013,0.0029,0.0024,0.0008,0.0030,1.0000,0.0010,0.0034,0.0007,-0.0008,0.0000,0.0010,0.0016,-0.0014,-0.0014
fe_12,-0.0032,0.0008,0.0010,0.0004,0.0006,0.0034,-0.0015,-0.0014,0.0020,-0.0061,0.0010,1.0000,-0.0039,0.0015,-0.0024,0.0011,-0.0014,0.0001,0.0035,0.0030
fe_13,0.0003,-0.0040,0.0004,-0.0011,0.0016,-0.0009,0.0001,-0.0027,-0.0012,-0.0009,0.0034,-0.0039,1.0000,0.0016,-0.0007,-0.0017,0.0023,0.0025,-0.0028,0.0017
fe_14,-0.0000,0.0033,-0.0036,-0.0021,-0.0001,-0.0030,0.0001,-0.0050,0.0013,-0.0019,0.0007,0.0015,0.0016,1.0000,0.0013,-0.0016,0.0029,0.0014,-0.0004,0.0011
fe_15,-0.0023,-0.0014,-0.0019,-0.0015,0.0024,0.0013,-0.0059,0.0045,-0.0005,0.0032,-0.0008,-0.0024,-0.0007,0.0013,1.0000,0.0013,0.0030,-0.0025,-0.0025,0.0007
fe_16,0.0018,-0.0035,0.0026,-0.0011,0.0010,0.0020,0.0020,-0.0001,0.0009,-0.0016,0.0000,0.0011,-0.0017,-0.0016,0.0013,1.0000,-0.0006,0.0047,0.0008,-0.0007
fe_17,0.0025,-0.0002,0.0011,-0.0017,-0.0010,0.0025,0.0048,-0.0027,0.0013,0.0013,0.0010,-0.0014,0.0023,0.0029,0.0030,-0.0006,1.0000,-0.0001,0.0011,0.0011
fe_18,-0.0023,-0.0004,0.0004,-0.0007,0.0008,-0.0009,0.0016,0.0030,0.0014,-0.0007,0.0016,0.0001,0.0025,0.0014,-0.0025,0.0047,-0.0001,1.0000,0.0035,0.0028
fe_19,-0.0010,0.0001,0.0015,0.0010,-0.0003,0.0046,-0.0009,-0.0031,0.0017,-0.0018,-0.0014,0.0035,-0.0028,-0.0004,-0.0025,0.0008,0.0011,0.0035,1.0000,0.0004
fe_20,0.0011,-0.0002,0.0011,0.0011,0.0021,0.0020,0.0012,0.0009,0.0001,0.0009,-0.0014,0.0030,0.0017,0.0011,0.0007,-0.0007,0.0011,0.0028,0.0004,1.0000

Top absolute correlations:

     col_a  col_b    corr  abs_corr
89    fe_5  fe_10 -0.0143    0.0143
184  fe_10   fe_5 -0.0143    0.0143
164   fe_9   fe_5 -0.0123    0.0123
88    fe_5   fe_9 -0.0123    0.0123
69    fe_4  fe_10 -0.0112    0.0112
183  fe_10   fe_4 -0.0112    0.0112
142   fe_8   fe_3 -0.0097    0.0097
47    fe_3   fe_8 -0.0097    0.0097
68    fe_4   fe_9 -0.0095    0.0095
163   fe_9   fe_4 -0.0095    0.0095
182  fe_10   fe_3 -0.0082    0.0082
49    fe_3  fe_10 -0.0082    0.0082
62    fe_4   fe_3  0.0078    0.0078
43    fe_3   fe_4  0.0078    0.0078
64    fe_4   fe_5  0.0076    0.0076
83    fe_5   fe_4  0.0076    0.0076
148   fe_8   fe_9  0.0072    0.0072
167   fe_9   fe_8  0.0072    0.0072
187  fe_10   fe_8  0.0071    0.0071
149   fe_8  fe_10  0.0071    0.0071

**Observations:**
- Features are uncorrelated with each other, no redundant columns to drop

## Build Silver tables for `features_clickstream`

In [153]:
bronze_directory = "datamart/bronze/clickstream"
silver_directory = "datamart/silver/clickstream"

for snapshot_date in date_str_lst:
    utils.data_processing_silver_table.process_feature_clickstream_silver_table(
        snapshot_date,
        bronze_directory,
        silver_directory,
        spark
    )

loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_01_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_01_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_02_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_02_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_03_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_03_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_04_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_04_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_05_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_05_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_06_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_06_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_07_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_07_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_08_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_08_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_09_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_09_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_10_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_10_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_11_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_11_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_12_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_12_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_01_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_01_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_02_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_02_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_03_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_03_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_04_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_04_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_05_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_05_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_06_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_06_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_07_01.csv row count: 8974

saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_07_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_08_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_08_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_09_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_09_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_10_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_10_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_11_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_11_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_12_01.csv row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_12_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_01_01.csv row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_01_01.parquet